### ISSUE TITLE
Add option to start week on startingDate instead of ISO weekday

### ISSUE THREAD

**Issue by peacechen** [BugiDev/react-native-calendar-strip#10]
I've added the prop _useIsoWeekday_ to control whether to start the week on ISO weekday (default) or the startingDate. 

Pull request #9

**Comment by BugiDev** [comment]
@peacechen Thank you! I am merging it now.

**Comment by peacechen** [comment]
Thanks :)  Would you mind publishing the updated version to npm?

**Comment by BugiDev** [comment]
@peacechen published :)
