### ISSUE TITLE
Updating datesWhitelist on onWeekChanged event causes strange behavior

### ISSUE THREAD

**Issue by lgalant** [BugiDev/react-native-calendar-strip#100]
On week changes, I'm recalculating the value of the parameter passed to datesWhitelist through a redux store.  
My CalendarStrip code is this:

           <CalendarStrip
                         daySelectionAnimation={{type: 'background', highlightColor: '#009fef'}}
                         style={{height:100, paddingTop: 20, paddingBottom: 10}}
                         calendarHeaderStyle={{color: 'black'}}
                         calendarColor={'#FFFFFF'}
                         dateNumberStyle={{color: 'black'}}
                         dateNameStyle={{color: 'black'}}
                         highlightDateNameStyle={{color: 'white'}}
                         highlightDateNumberStyle={{color: 'white'}}
                         iconContainer={{flex: 0.1}}
                         styleWeekend={false}
                         datesWhitelist={this.props.datesWhiteList}
                         customDatesStyles={this.state.selectedDateMM.format("YYYYMMDD")==moment().format("YYYYMMDD")?[]:customDatesStyles}
                         onDateSelected={(day) =>  {this._selectDate.bind(this)(day)}}
                         onWeekChanged={(day) =>  {this._weekChanged.bind(this)(day)}}
                     />

The _weekChanged method calls redux action that queries a database and recalculates this.props.datesWhiteList to show the busy dates as available to click.  With that in place whenever I click the arrow and reach a week which contains a busy day, it gets stuck.  The next arrow does not move any further.
Please let me know if I'm doing something wrong or it's a bug in the library.
Thanks in advance!

**Comment by MargaretKrutikova** [comment]
@lgalant, I had a similar problem when dynamically changing `datesWhitelist` on week change (the week changes to the next one after a few clicks but then jumps back to the first week). The problem disappears though if you set `selectedDate` together with `datesWhitelist` (in my case I had to mark the first date from `datesWhitelist` as selected for each week). 

If you look at the source code of `CalendarStrip` and `componentDidUpdate` you see that three different cases of `props` change are processed and when `selectedDate` has changed you get into this [block](https://github.com/BugiDev/react-native-calendar-strip/blob/master/src/CalendarStrip.js#L157), but when only `datesWhitelist` has changed it skips all the way to this [code](https://github.com/BugiDev/react-native-calendar-strip/blob/master/src/CalendarStrip.js#L193) which I assume has a bug. Would be interesting to figure out where exactly the problem occurs and fix it, I can look into it when I get more time unless someone else will fix it by then :)

**Comment by lgalant** [comment]
Hi @MargaretKrutikova , I looked at that piece of code as well but wasn't sure if it was correct or not. I ended up making it work by adding this property:
 
   updateWeek={false}

Hope that helps

**Comment by peacechen** [comment]
Thanks @MargaretKrutikova for inspecting the props evaluation code.  If you have any suggestions on how to do it more cleanly, please submit a PR.  There are a lot of use cases and we should add more tests to make sure nothing breaks.

@lgalant  That's the right prop to use.  `updateWeek` was implemented specifically for cases where other props changing trigger a week update.  But in your case you don't want that to happen.

**Comment by MargaretKrutikova** [comment]
Thanks @lgalant! I tried setting `updateWeek` to `false` and it does work properly now, I guess I didn't understand the purpose of this `prop` from the docs ...
