### ISSUE TITLE
Unable to change color of left and right navigation icon

### ISSUE THREAD

**Issue by sureshmurali** [BugiDev/react-native-calendar-strip#103]
Current version's navigation icon is an Image. Its better to make the default navigation icon as Text icon. So that we can change the color by giving` iconStyle={{color:'white'}}`.

**Comment by peacechen** [comment]
Using an icon would mean adding another dependency (e.g. `react-native-vector-icons`), which usually means native code changes involving `react-native link`.  Some people are ok with that, others with existing app store deployments may not want to go through releasing a new version just for this.

You can replace the left & right selector icons entirely with your own icon component.  See the `leftSelector` and `rightSelector ` props:
https://github.com/BugiDev/react-native-calendar-strip#icon-sizing

**Comment by sureshmurali** [comment]
Got it. Thanks for the clear explanation.
