### ISSUE TITLE
minDate doesn't work as expected ?

### ISSUE THREAD

**Issue by vince83110** [BugiDev/react-native-calendar-strip#105]
Thanks for this plugin, it's pretty nice.

But, I want to use it as a DatePicker only for at leat today. So I used minDate property set to : 

`minDate={moment()}`

I can't previous the last week, but I can pick dates of the week previous to today. Is there a way to only allow user to pick a date after today (or today) ? 

Thanks

**Comment by peacechen** [comment]
Try the `datesBlacklist` prop.
https://github.com/BugiDev/react-native-calendar-strip#initial-data-and-ondateselected-handler

```
// Date range format
 let datesBlacklist = {
      start: moment(0), // the "beginning of time", in Unix time
      end: moment().subtract(1, 'day')  // yesterday
  }
```
Pass that to CalendarStrip as a prop `datesBlacklist={datesBlacklist}`

**Comment by vince83110** [comment]
Hello, yes I think it's the best way.

By the way, datesBlackList expects an array : 

```
let datesBlacklist = [{
      start: moment(0), // the "beginning of time", in Unix time
      end: moment().subtract(1, 'day')  // yesterday
}]
```

Thanks

**Comment by nppull** [comment]
```
let datesBlacklist = [{
      start: moment(0), // the "beginning of time", in Unix time
      end: moment().subtract(1, 'day')  // yesterday
}]
```
thank u, this code help me
