### ISSUE TITLE
when i call setSelectedDate, selected date update but weekData not update

### ISSUE THREAD

**Issue by jacktv1** [BugiDev/react-native-calendar-strip#107]
when i call setSelectedDate, selected date update but weekData not update

**Comment by peacechen** [comment]
There was discussion about this in #90 

An additional parameter may be needed in `setSelectedDate` to get it to update the week view.  For example
```
setSelectedDate(moment('12-25-1990'), true);
```
Would set the selected date *and* move the week to that date.

PRs are welcome.  It may be some time until I can get to this.

**Comment by peacechen** [comment]
The `updateWeekView` method has been added in 2.0.0.

**Comment by TaLevy94** [comment]
Hi. I found the solution, I guess...

you should update the selectedDate property and starting date dynamically, when handling onDateSelected event
