### ISSUE TITLE
Disable selection of future dates

### ISSUE THREAD

**Issue by sood03** [BugiDev/react-native-calendar-strip#11]
I have a scenario where I want to disable selection of any date in future. Can I implement that now by enabling any props?

**Comment by peacechen** [comment]
I would also find this feature useful.  I plan to create a PR to implement this soon.

**Comment by peacechen** [comment]
I've implemented this with whitelist and blacklist props.  Waiting on @BugiDev to merge a few other PR's so that the commits don't intermingle.

**Comment by peacechen** [comment]
Created PR #20 that adds props to enable/disable dates & date ranges.

**Comment by peacechen** [comment]
Merged PR #20 which implements this feature.
