### ISSUE TITLE
( Localization issue ) App stopped working when opened after installing apk

### ISSUE THREAD

**Issue by ImHamzaAnwer** [BugiDev/react-native-calendar-strip#110]
I changed the locale object for Chinese, app is working fine on emulator but when i build and install apk, app stops working.

**Comment by peacechen** [comment]
Please post the `<CalendarStrip>` code.  Are you `require`ing the locale file?  Android can rename files when creating the APK, causing the require to fail to load.

Recommend that you run the release build in Android Studio to see the error messages when it crashes.

**Comment by ImHamzaAnwer** [comment]
`const locale = {
    name: 'zh',
    config: {
        months: '一月_二月_三月_四月_五月_六月_七月_八月_九月_十月_十一月_十二月'.split('_'),
        monthsShort: '1月_2月_3月_4月_5月_6月_7月_8月_9月_10月_11月_12月'.split('_'),
        weekdays: '星期日_星期一_星期二_星期三_星期四_星期五_星期六'.split('_'),
        weekdaysShort: '日_一_二_三_四_五_六'.split('_'),
        weekdaysMin: '日_一_二_三_四_五_六'.split('_'),
        longDateFormat: {
            LT: 'HH:mm',
            LTS: 'HH:mm:ss',
            L: 'YYYY/MM/DD',
            LL: 'YYYY年M月D日',
            LLL: 'YYYY年M月D日 HH:mm',
            LLLL: 'YYYY年M月D日dddd HH:mm',
            l: 'YYYY/M/D',
            ll: 'YYYY年M月D日',
            lll: 'YYYY年M月D日 HH:mm',
            llll: 'YYYY年M月D日dddd HH:mm'
        },
        meridiemParse: /凌晨|早上|上午|中午|下午|晚上/,
        meridiemHour: function (hour, meridiem) {
            if (hour === 12) {
                hour = 0;
            }
            if (meridiem === '凌晨' || meridiem === '早上' || meridiem === '上午') {
                return hour;
            } else if (meridiem === '中午') {
                return hour >= 11 ? hour : hour + 12;
            } else if (meridiem === '下午' || meridiem === '晚上') {
                return hour + 12;
            }
        },
        meridiem: function (hour, minute, isLower) {
            var hm = hour * 100 + minute;
            if (hm < 600) {
                return '凌晨';
            } else if (hm < 900) {
                return '早上';
            } else if (hm < 1130) {
                return '上午';
            } else if (hm < 1230) {
                return '中午';
            } else if (hm < 1800) {
                return '下午';
            } else {
                return '晚上';
            }
        },
        calendar: {
            sameDay: '[今天]LT',
            nextDay: '[明天]LT',
            nextWeek: '[下]ddddLT',
            lastDay: '[昨天]LT',
            lastWeek: '[上]ddddLT',
            sameElse: 'L'
        },
        dayOfMonthOrdinalParse: /\d{1,2}(日|月|週)/,
        ordinal: function (number, period) {
            switch (period) {
                case 'd':
                case 'D':
                case 'DDD':
                    return number + '日';
                case 'M':
                    return number + '月';
                case 'w':
                case 'W':
                    return number + '週';
                default:
                    return number;
            }
        },
        relativeTime: {
            future: '%s內',
            past: '%s前',
            s: '幾秒',
            ss: '%d 秒',
            m: '1 分鐘',
            mm: '%d 分鐘',
            h: '1 小時',
            hh: '%d 小時',
            d: '1 天',
            dd: '%d 天',
            M: '1 個月',
            MM: '%d 個月',
            y: '1 年',
            yy: '%d 年'
        }
    }
};`

` <CalendarStrip
                    locale={locale}
                    useIsoWeekday={false}
                    onDateSelected={(date) => this.setState({ selectedDate: date })}
                    startingDate={this.state.selectedDate}
                    style={{ width: "85%", paddingVertical: 5 }}
                    innerStyle={{ margin: 0, padding: 0 }}
                    showMonth={false}
                    daySelectionAnimation={{ type: 'background', duration: 200, highlightColor: '#00adf5', }}
                    dateNumberStyle={{ color: '#ccc', }}
                    dateNameStyle={{ color: '#ccc' }}
                    highlightDateNameStyle={{ color: "#fff" }}
                    highlightDateNumberStyle={{ color: "#fff" }}
                    iconContainer={{ display: "none" }}
                    shouldAllowFontScaling={false}
                    responsiveSizingOffset={-2}
                />`

**Comment by gokhanamal** [comment]
I have same error. I can't fix it.

**Comment by peacechen** [comment]
This guy may have found a solution:
https://stackoverflow.com/questions/49637158/react-native-release-crash-because-of-unkown-module-momentjs-locale

> I'm creating an React-Native App, which is working fine on the emulator on DEBUG mode. However, when I tried on on RELEASE mode, it crashes because of a failing module.
> 
> The ADB Logcat points to this message as a cause of the exception:
> 
> ```
>  ReactNativeJS: Requiring unknown module "./locale/pt-br".
> ```
> I know it's being caused by a call to method "updateLocale" of momentJS library. This call is placed inside the "react-native-calendar-strip" component, when I need to set a different locale options.
> 
> I've tried a lot of different combinations on import statements, none of them working.
> 
> This is what I tried:
> 
> ```
> import moment from 'moment';
> import 'moment/locale/pt-br';
> ```
> or
> 
> ```
> import moment from 'moment/min/moment-with-locales';
> ```
> 
> I also tried to require the locale
> ```
> require('moment/locale/pt-br'); 
> ```
> 
> --------------------------------------------------------------------------------
> 
> I just figured out the solution:
> 
> I organized my imports like this:
> ```
> import 'moment';
> import 'moment/locale/pt-br';
> import moment from 'moment-timezone';
> ```
> Then, on the beginning of the code, I had set the locale manually, before the react-native-calendar-strip could call the updateLocale method, like this:
> 
> ```
> moment().locale('pt-br');
> ```

**Comment by peacechen** [comment]
@ImHamzaAnwer @gokhanamal 
Were you able to resolve the crash?

**Comment by ibrahimokdadov** [comment]
I've actually had the same issue and was able to resolve using the link shared. 
The solution is as:
- you need to import the right locale... import 'moment/locale/es-do';  after you import moment.
- In the locale prop in CalendarStrip make sure the name matches the import above. so locale ={name:'es-do', config:....}

**Comment by GaetanB999** [comment]
Hello,

I have the same issue and I don't find a way to fix it.
I use : 
"i18n-js" (3.2.1) 
"react-native-localize" (1.1.2) 
"react" (16.6.1)
"react-native" (0.57.7)

I tried the solution above, without success.

```
import React, { Component } from "react";
import PropTypes from "prop-types";
import I18n from "../I18n/I18n";
import "../I18n/languages/en";
import "../I18n/languages/fr";
import "../I18n/languages/nl";
import CalendarStrip from "react-native-calendar-strip";

// Styles
import styles from "./Styles/CalendarStyle";
import Colors from "../Themes/Colors";

const locale = {
  name: I18n.locale.substr(0, 2).toLowerCase(),
  config: {
    months: I18n.t("Common.MonthsName"),
    monthsShort: I18n.t("Common.monthNamesShort"),
    weekdays: I18n.t("Common.dayNames"),
    weekdaysShort: I18n.t("Common.dayNamesShort"),
    weekdaysMin: I18n.t("Common.dayNamesMin")
  }
};
```

```
<CalendarStrip
        style={styles.calendarWeek}
        selectedDate={this.props.selectedDate}
        onDateSelected={this.props.onDateSelected}
        onWeekChanged={this.props.onWeekChanged}
        highlightDateNumberStyle={{ color: "white" }}
        highlightDateNameStyle={{ color: "white" }}
        daySelectionAnimation={{ type: "background", highlightColor: Colors.gsa_azur }}
        locale={locale}
        markedDates={cal_MarkedDates}
/>
```


any idea ?
Thanks.

**Comment by peacechen** [comment]
Please read the StackOverflow answer as well as @ibrahimokdadov 's post.  You need to import the corresponding Moment locale module for the language you like.  You're setting it to:
```
  name: I18n.locale.substr(0, 2).toLowerCase(),
```
Whatever language name string that resolves to, you should import the moment language module for it.

**Comment by GaetanB999** [comment]
@peacechen Thank you for answering.
I did not understand what was the "Moment locale module" ... now it is clear and it's working :-)
