### ISSUE TITLE
Date Number Style and Day Number Style not working.

### ISSUE THREAD

**Issue by wmlutz** [BugiDev/react-native-calendar-strip#112]
Both the Day and Date Number styles seem to be not working and I cannot figure out why.

I am trying to make the style responsive to a dark/light background. But the text color is black whether the background is black or white.

I have checked on text_color below via the console to make sure it isn't a tinycolor issue. And used a direct string value for color: `{color: 'red'}` - neither are working.

Here's my component:
```
import React, {Component} from 'react';
import { View } from 'react-native';
import CalendarStrip from 'react-native-calendar-strip';
import {AppContext} from './ContextProvider';
import tinycolor from 'tinycolor2';

class CalStrip extends Component {
  render() {
    const {header_color} = this.props;
    var color1 = tinycolor(header_color);
    var text_color = color1.isDark() ? '#fff' : '#000';

    return (
      <View>
        <AppContext.Consumer>
          {(context) =>
            <CalendarStrip
              calendarAnimation={{type: 'sequence', duration: 10}}
              daySelectionAnimation={{type: 'border', duration: 200, borderWidth: 1, borderHighlightColor: text_color}}
              style={{height: 100, paddingTop: 20, paddingBottom: 10}}
              calendarHeaderStyle={{color: text_color}}
              calendarColor={color1.toHexString()}
              dateNumberStyle={{color: text_color}} // Not working XXX
              dateNameStyle={{color: text_color}} // Not working XXX
              highlightDateNumberStyle={{color: text_color}}
              highlightDateNameStyle={{color: text_color}}
              disabledDateNameStyle={{color: 'grey'}}
              disabledDateNumberStyle={{color: 'grey'}}
              iconContainer={{flex: 0.1}}
              onDateSelected={(value) => context.setDate(value)}
              selectedDate={context.date}
            />
          }
        </AppContext.Consumer>
      </View>
    )
  }
}

export default CalStrip;
```

And this is what the output looks like:
![cal_strip_screenshot](https://user-images.githubusercontent.com/6496048/46572472-321d0a80-c954-11e8-96f0-5f9cfad09fb9.PNG)

**Comment by eyalabadi98** [comment]
Hey! 

How did you incorporate the daily calendar with the 2 appointments? Sorry it has nothing to do with your issue but I'm just wondering if its something inbuilt or an external package

**Comment by wmlutz** [comment]
@eyalabadi98 - I've been building [RN Schedule](https://github.com/wmlutz/rnschedule) for the community to use. Bc of this issue I used wix's cal with a drop down. If you like the RNSchedule library let me know. I'm working on it in my free time.

**Comment by samuelwilso** [comment]
Its still not working

**Comment by peacechen** [comment]
Are you pointing directly to this repo?

> I committed the fix to this repo but haven't published on npm yet. If someone doesn't mind testing it, point to this repo directly in the package.json

**Comment by DomCostantino** [comment]
@peacechen i've the same issue, my code is this: 
`<CalendarStrip
              calendarAnimation={{type: 'sequence', duration: 30}}
              daySelectionAnimation={{type: 'border', duration: 200, borderWidth: 1, borderHighlightColor: 'white'}}
              style={{flex: 1, paddingTop: 20, paddingBottom: 10}}
              calendarHeaderStyle={{color: Colors.primaryColor}}
              calendarColor={''}
              dateNumberStyle={{color:'white'}}
              dateNameStyle={{color:'white'}}
              highlightDateNumberStyle={{color: Colors.primaryColor}}
              highlightDateNameStyle={{color: Colors.primaryColor}}
            />`
text color white is not applied

**Comment by makenova** [comment]
@peacechen I can confirm that pointing directly at the repo as you suggested works.

Can you cut a new release on npm?

**Comment by arulmuthunas** [comment]
![Screenshot 2020-08-06 at 1 34 19 PM](https://user-images.githubusercontent.com/42431888/89508041-f7ec5080-d7ea-11ea-9b4f-48dd20220846.png)
this is my current calendar modal
![Screenshot 2020-08-06 at 1 34 31 PM](https://user-images.githubusercontent.com/42431888/89508069-05093f80-d7eb-11ea-97a4-4e4886a4dde7.png)
but i want like this 
please tell me to how to set border radiusin selecteddate

**Comment by peacechen** [comment]
A new prop needs to be added to set the container's style. Please open a new issue, or submit a PR that adds a `highlightDateContainerStyle`.

https://github.com/BugiDev/react-native-calendar-strip/blob/686bdb501dd5c993c6eb7021a4967736b6579353/src/CalendarDay.js#L454

**Comment by MaryamKhan05** [comment]
i want to make my calendar look like this 
<img width="327" alt="Screenshot 2023-05-31 at 10 40 10 PM" src="https://github.com/BugiDev/react-native-calendar-strip/assets/97352704/afd940df-b94b-4726-8963-a0582252a464">
but it is looking like this 
<img width="221" alt="Screenshot 2023-05-31 at 10 40 40 PM" src="https://github.com/BugiDev/react-native-calendar-strip/assets/97352704/26bfe4c0-a7ae-4ee3-92b7-8012a5228d5a">
how can i add the background color to other name and dates too ?
