### ISSUE TITLE
!! Not Issue. But Can I select day by day, I don't want get datesWhitelist Array.

### ISSUE THREAD

**Issue by trancanh2202** [BugiDev/react-native-calendar-strip#113]
I saw example code datesWhitelist:
    let datesWhitelist = [{
            start: moment("2018-10-17"),
            end: moment("2018-10-20")
    }];  => it will show array days : 17 18 19 20
I just want choose 17 and 20. How can I do it. Please help me.

**Comment by peacechen** [comment]
If you mean select multiple, arbitrary dates, this was requested in #80.  No one has submitted a PR to implement it.

**Comment by peacechen** [comment]
@trancanh2202 
After re-reading your OP, I think I understand what you wanted.  To enable individual dates, pass the dates directly as values in the array (not as an object).
```
let datesWhitelist = [
  "2018-10-17",
  "2018-10-20",
];
```
