### ISSUE TITLE
How can I add a marker ?

### ISSUE THREAD

**Issue by hellpirat** [BugiDev/react-native-calendar-strip#117]
How can I add a marker to day? 

Something like in this library https://github.com/wix/react-native-calendars 

markedDates={{ }}

**Comment by peacechen** [comment]
Use the `onDateSelected` callback to set the `customDatesStyles` prop.
https://github.com/BugiDev/react-native-calendar-strip#customdatesstyles

Note that the selected date will be highlighted with the default styling.  To prevent that, use props `highlightDateNameStyle` and `highlightDateNumberStyle` to override it.

**Comment by hellpirat** [comment]
> Use the `onDateSelected` callback to set the `customDatesStyles` prop.
> https://github.com/BugiDev/react-native-calendar-strip#customdatesstyles
> 
> Note that the selected date will be highlighted with the default styling. To prevent that, use props `highlightDateNameStyle` and `highlightDateNumberStyle` to override it.

yes, I did found this and even change color and background for highlight item. But I need to add little dot under date number

**Comment by hellpirat** [comment]
I will fork and trying to add this feature :)

**Comment by peacechen** [comment]
PRs are welcome.  Thanks for working on a new feature.
