### ISSUE TITLE
minDate - why can you still go back?

### ISSUE THREAD

**Issue by quangas** [BugiDev/react-native-calendar-strip#118]
Does the minDate prop work properly?

If I set a `minDate={moment()}`, I can still hit the back button and it will show me dates before that. How can I disable the back button and not show any dates before the minDate?

**Comment by peacechen** [comment]
The `minDate` prop should prevent dates from being selected, but it doesn't stop the back button from going to previous weeks.  That would be a good feature enhancement.  PRs are welcome 👍

**Comment by quangas** [comment]
You can still select dates from being selected even with minDate prop set.

**Comment by peacechen** [comment]
My mistake, I was thinking of the `datesBlacklist` prop.  `minDate` should prevent the week navigation buttons from moving before that date.  The logic is here:
https://github.com/BugiDev/react-native-calendar-strip/blob/2944f3c3ebe5d09ab1727867f287908486d5a0ab/src/WeekSelector.js#L46

Please post your `<CalendarStrip>` code.  Are you setting the initial date before today's current week?

**Comment by LeviWilliams** [comment]
Try using the `datesWhitelist` prop like this:

`datesWhitelist={[{
      start: this.props.startDateFormatted,
      end: this.props.endDateFormatted
  }]}`

**Comment by usmanf8c** [comment]
@LeviWilliams that is a good solution.

I have found a similar issue before coming across LeviWilliams' solution.

To help explain, today is a Tuesday.
There is no back arrow so I can't go back a week, there is a forward arrow (to go to next week).
If I was to click on Monday, it was taking me to the previous week (this seems to be where I had a problem that I haven't solved - yet!).

However, here is a working snack to show minDate working :)

[https://snack.expo.io/rJ4GAg85B](https://snack.expo.io/rJ4GAg85B)
