### ISSUE TITLE
Text color inside highlighted date

### ISSUE THREAD

**Issue by peacechen** [BugiDev/react-native-calendar-strip#12]
I'd like to style the text inside highlighted date.  The use case is to create an inverted color scheme on the highlighted date.  The highlightColor option enabled styling of the color, but if both the text and highlightColor are dark it's harder to read.  For example:

![image](https://cloud.githubusercontent.com/assets/6295083/21626611/b34d8dc6-d1d7-11e6-82c8-e98453f2d803.png)

It would look better if the text inside the highlighted date (Thu 5 in this case) is white.

**Comment by peacechen** [comment]
Created PR #13 which implements this feature.  An example followed by the code to create it:

![image](https://cloud.githubusercontent.com/assets/6295083/21649842/b227d0d2-d268-11e6-8d5a-c525d5636919.png)

```
<CalendarStrip
	selection={'background'}
	calendarColor={'transparent'}
	highlightColor={'#3a9fbd'}
	highlightDateNumberStyle={{color: 'white'}}
	highlightDateNameStyle={{color: 'white'}}
	styleWeekend={false}
/>
```

If you find this acceptable, please publish to npm after merging.  Thanks!

**Comment by BugiDev** [comment]
@peacechen Thanks for the PR! Merged and published.
