### ISSUE TITLE
onDateSelected returns same date everytime

### ISSUE THREAD

**Issue by LeviWilliams** [BugiDev/react-native-calendar-strip#120]
I have a CalendarStrip which I want to use with a function that updates state every time the date is changed - I am trying to leverage it to display data depending on the day similar to Tabs. Each time a new date is selected  onDateSelected returns the exact same moment timestamp.

Example: https://ibb.co/XDn7tPW

CalendarStrip (styling props removed):

```
<CalendarStrip
   ref={(c) => { this._calendarStrip = c; }}
   onDateSelected={date => console.log(date)}
   selectedDate={this.props.startDateFormatted}
   minDate={this.props.startDateFormatted}
   maxDate={this.props.endDateFormatted}
   datesWhitelist={[{
      start: this.props.startDateFormatted,
      end: this.props.endDateFormatted
  }]}
/>
```
_onDateSelected:

```
_onDateSelected(date) {
    this.setState({daySelected: date});
    console.log(date);
  }
```

**Comment by peacechen** [comment]
Try removing the `selectedDate` prop.  It should work either way, but let's rule that out at least.

**Comment by LeviWilliams** [comment]
That fixes it - problem is selectedDate is a necessary prop in what I am trying to achieve.

**Comment by LeviWilliams** [comment]
Actually if I switch `onDateSelected={date => console.log(date)}` to `onDateSelected={date => console.log(date.valueOf())}` it works for some reason. How does that make sense?

**Comment by LeviWilliams** [comment]
Even just using static values for testing the same problem persisted. At least I am able to use it now that the `.valueOf()` returns the correct milliseconds.

**Comment by peacechen** [comment]
That's a bit concerning and maybe a potential bug.  Try to use Moment to format the date:
```
   onDateSelected={date => console.log(date.format('MM-DD-YYYY')}
```

It could be that the built-in JS date formatter has an issue with Moment objects.
