### ISSUE TITLE
Unable to set the first day of the week in locale config

### ISSUE THREAD

**Issue by pavermakov** [BugiDev/react-native-calendar-strip#122]
Here is my locale config:
`
{
        name: moment.locale(),
         config: {
                        months: moment.months(),
                        weekdaysShort: moment.weekdaysShort(),
                        week: {
                            dow: 0
                        }
                    }
                }
`

I have set `week.dow` to 0 and expected to see Sunday as the first day, however, I saw Monday instead. Am I doing something wrong?

**Comment by peacechen** [comment]
I believe you'll need to use the `useIsoWeekday` and `startingDate` props.

Refer the props documentation
https://github.com/BugiDev/react-native-calendar-strip#initial-data-and-ondateselected-handler
