### ISSUE TITLE
getSelectedDate() returns the wrong current date

### ISSUE THREAD

**Issue by gethabit** [BugiDev/react-native-calendar-strip#124]
getSelectedDate() is returning the wrong dates

`  <CalendarStrip
            ...
            ref={component => this._calendar = component}
       />
  `

`
alert(this. _calendar.getSelectedDate())
`

**Comment by Farhankhalid33100** [comment]
@gethabit  this is not wrong . function return us time in mili seconds.
try this ,
moment(1454521239279).format("DD MMM YYYY hh:mm a") 
hope its your desired result.

**Comment by peacechen** [comment]
What is the sequence of events?  Do you call `getSelectedDate` immediately after the CalendarStrip is instantiated?   ... or do you first select a date, then call `getSelectedDate` ?
