### ISSUE TITLE
Setting current say as markedDate

### ISSUE THREAD

**Issue by vladromila** [BugiDev/react-native-calendar-strip#125]
Hi guys. I have been trying to set the current day as a markedDate but this doesn't seem to work. I have literally tried all data formats. Thanks!
`markedDates={
                    [
                        {
                            date: new Date(),
                            dots: [
                                {
                                    key: 0,
                                    color: 'red',
                                    selectedDotColor: 'red',
                                },
                            ],
                        },
                    ]
                }`

**Comment by peacechen** [comment]
@hellpirat 
Any insight on how to get marked dates working for @vladromila  ?

**Comment by makenova** [comment]
@vladromila what you have seems to work when I put it into a [snack](https://snack.expo.io).
What are you seeing that makes you believe it is not working?

```js
import * as React from 'react';
import { SafeAreaView, StyleSheet } from 'react-native';
import CalendarStrip from 'react-native-calendar-strip';

export default class App extends React.Component {
  render() {
    return (
      <SafeAreaView style={styles.container}>
        <CalendarStrip
          markedDates={[
            {
              date: new Date(),
              dots: [{ key: 0, color: 'red', selectedDotColor: 'blue' }],
            },
          ]}
          style={{ height: 150, paddingTop: 20, paddingBottom: 10 }}
        />
      </SafeAreaView>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
});
```

The above code in a snack gives me this:

![img_ca12508c9992-1](https://user-images.githubusercontent.com/941708/52969672-c1144780-3376-11e9-80c8-e33870a05ad5.jpeg)

**Comment by slo74design** [comment]
Hi, I would like to set multiple dates but I'm having a lot of issues.
```
    const markedDates = [
        {
            date: moment(
                ["2023-10-10", "2023-10-11", "2023-10-11", "2023-10-12"],
                "yyyy-mm-dd"
            ),
            dots: [
                {
                    color: "red",
                },
            ],
        },
    ];
```
