### ISSUE TITLE
Question: How do I draw a circle around the date number?

### ISSUE THREAD

**Issue by makenova** [BugiDev/react-native-calendar-strip#128]
I would like to draw a circle around just the date number but because of the responsive stying, it may look fine on one device but really bad on another.
This is what I am trying to achieve:

![screen shot 2019-02-18 at 11 45 38 am](https://user-images.githubusercontent.com/941708/52968476-eacb6f80-3372-11e9-9e82-3b8088f34efa.png)

but on some devices such as the One Plus 6, I get this instead:

![screenshot_20190218-115712](https://user-images.githubusercontent.com/941708/52969141-f455d700-3374-11e9-9097-99e9030fbc83.jpg)

It breaks in other ways on different devices.

**Comment by peacechen** [comment]
The responsive scaling doesn't adapt to the myriad of screen resolutions and densities, unfortunately.  The prop `responsiveSizingOffset` allows for manual adjust it though.
https://github.com/BugiDev/react-native-calendar-strip#responsive-sizing

**Comment by makenova** [comment]
@peacechen Thank you. I'll give that a try.

**Comment by peacechen** [comment]
I haven't had time to implement more intelligent responsive sizing.  If anyone would like to take a shot please submit a PR.  The first step would be to scale based on DPI and not just container size.  That should be able to accommodate a wider range of display resolutions and densities.  The next improvement may be to have separate values for iOS vs Android.  And finally after that, a lookup table for specific "problem devices" that don't render well with the general formulas.

**Comment by gveraperea** [comment]
I'm sorry to re open this, but just having the same issue, i was wondering how did you manage to draw a circle around the date number and if the problems with different resolutions got fixed?

**Comment by makenova** [comment]
@gveraperea I was not able to resolve this issue. I simply try to make it look decent on the top devices our customers use based on analytics.
Pardon the delayed reply.

**Comment by peacechen** [comment]
@gveraperea 
PRs are welcome.  As I mentioned previously, the responsive sizing should take into account DPI in addition to container size.  There are so many variations especially on Android that I don't have access to test on.

**Comment by anhquan291** [comment]
> I'm sorry to re open this, but just having the same issue, i was wondering how did you manage to draw a circle around the date number and if the problems with different resolutions got fixed?
Hi everyone,
I would like to do the same,  only draw a circle around the date number. Please help. Thank you so much

**Comment by peacechen** [comment]
Use the sample app in this project to create a reproducible demo. Paste the `<CalendarStrip>` props here along with the device you're testing on. A device type that's reproducible in an emulator would be ideal.
Remember to set sufficient container height that CalendarStrip is housed in.
