### ISSUE TITLE
Adding Week number on the strip

### ISSUE THREAD

**Issue by JonasOmdal** [BugiDev/react-native-calendar-strip#129]
Is it possible to add week number to the calender strip like this?
![bilde](https://user-images.githubusercontent.com/25055755/53005166-f8482e80-3432-11e9-92f9-0f583a523c03.png)

**Comment by peacechen** [comment]
It is possible.  PR's are welcome 😄

**Comment by peacechen** [comment]
This `headerText` prop is available on master.  This allows you to format the header any way you like.  As per the documentation,
>Use with onWeekChanged to receive the visible start & end dates.

https://github.com/BugiDev/react-native-calendar-strip#initial-data-and-ondateselected-handler
