### ISSUE TITLE
Not Issue, HELP!

### ISSUE THREAD

**Issue by marketmix-matteoquintero** [BugiDev/react-native-calendar-strip#131]
I am new to react, someone can help me with showing an example of how to use the function.
`getSelectedDate()`

Please and thank you. @BugiDev

**Comment by peacechen** [comment]
This would be a helpful addition to the documentation.  PRs are welcome.

**Comment by usmanf8c** [comment]
Hi,

Quick snack here!

[https://snack.expo.io/S1YlKFa9H](https://snack.expo.io/S1YlKFa9H)

Hope this helps.

**Comment by peacechen** [comment]
Thanks for the snack @usmanf8c 

@marketmix-matteoquintero Usually the best way to get the selected date is through the `onDateSelected` callback.
https://github.com/BugiDev/react-native-calendar-strip/issues/155#issuecomment-548364620

**Comment by usmanf8c** [comment]
@peacechen - I thought the same. `onDateSelected` does return the selected date, but I thought I'd stick to the topic and draft up a snack using the `getSelectedDate()` method. Hope it helped @marketmix-matteoquintero .
