### ISSUE TITLE
Custom Day Component

### ISSUE THREAD

**Issue by toxicsebastian** [BugiDev/react-native-calendar-strip#132]
I'm trying to modify the day-component because I want to fetch certain data and present it along with the date. Is there any chance of this getting implemented or is there already a way to do it? Like for instance in the **react-native-calendars library** (see code below), you can pass a component to the prop "dayComponent" and pretty much do whatever you want inside your component as you also get the props date and state.

```
dayComponent={({ date, state }) => {
  return ( <DayComponent /> );
}}
```

/ Seb

**Comment by peacechen** [comment]
It should be relatively straight-forward to substitute the built-in Day component with one supplied via props.  The caller of the library would need to do a lot of work to recreate the Day component.
https://github.com/BugiDev/react-native-calendar-strip/blob/master/src/CalendarDay.js

Would you be interested in submitting a PR?

**Comment by peacechen** [comment]
I took a stab at this.  Please test it out by pointing your package.json directly to this repo.

**Comment by peacechen** [comment]
@toxicsebastian  Any feedback on this feature?

**Comment by peacechen** [comment]
This feature was added in 1.3.8 with the `dayComponent` prop.

**Comment by iandonov** [comment]
@peacechen 
I am trying to use this functionality but have some issue with implementation:
Can you help me understand what is wrong?
I am calling it like that:

```
<CalendarStrip
..
dayComponent={() => {
    return ( <CalendarStripDay /> );
    }}

/>
```

But I don't get any props in the CalendarStripDay component function:
`export default function CalendarStripDay(props) {..}`

It is actualy called.
Thanks

**Comment by iandonov** [comment]
> @peacechen
> I am trying to use this functionality but have some issue with implementation:
> Can you help me understand what is wrong?
> I am calling it like that:
> 
> ```
> <CalendarStrip
> ..
> dayComponent={() => {
>     return ( <CalendarStripDay /> );
>     }}
> 
> />
> ```
> 
> But I don't get any props in the CalendarStripDay component function:
> `export default function CalendarStripDay(props) {..}`
> 
> It is actualy called.
> Thanks

OK found that I need to set it like that:
`dayComponent={CalendarStripDay}`

**Comment by peacechen** [comment]
Yes that's correct.  If you encounter any other problems, please open a new issue.
