### ISSUE TITLE
How to disable on press date ?

### ISSUE THREAD

**Issue by huynguyen2903** [BugiDev/react-native-calendar-strip#138]
How can I disable on press onDateSelected?. 
Thanks!

**Comment by peacechen** [comment]
Use the `datesBlacklist` prop:
https://github.com/BugiDev/react-native-calendar-strip#initial-data-and-ondateselected-handler

**Comment by hani-q** [comment]
Actually this is a different question,  I make an axio call each time a day is pressed. I want the calendar header to be disabled for selection of any further dates until the call has returned some data 

Can i pass isFecthing bool anywhere to the component to disable it during the fetch request ?

**Comment by peacechen** [comment]
You could try to pass a height of 0 to `calendarHeaderContainerStyle`.  If that doesn't work, a new prop would need to be added.
Please open a new issue for different topics.
