### ISSUE TITLE
Responsive design

### ISSUE THREAD

**Issue by peacechen** [BugiDev/react-native-calendar-strip#14]
This library would benefit from [Responsive design](https://en.wikipedia.org/wiki/Responsive_web_design).  It currently renders only one size which takes up too much space on smaller screen such as phones.  I've found [React Native Style Tachyons](https://github.com/tachyons-css/react-native-style-tachyons) quite useful in sizing fonts and containers programmatically to the screen size.  I propose passing in a _rem_ prop to allow the user of this library some control over the scaling.  React Native Calendar Strip would use that value internally with React Native Style Tachyons to auto scale its fonts and containers.

Alternatively (or in addition), an _autoSize_ prop could automatically size the Calendar Strip to its container.

**Comment by peacechen** [comment]
There are a number of issues and enhancements that I'm planning and working on.  @BugiDev 's PR merging takes weeks to months which is too slow for our projects.  I'd like to request write access in order to merge PR's.  Otherwise I'll have to move forward on a fork of this great project and publish it separately.

**Comment by BugiDev** [comment]
@peacechen I haven't been able to work on this library lately unfortunately, but would definitely want to see this project alive. We can continue working on this together, so I have sent you the invitation for collaborator and given you access to repo. Could you please send me an email so we can discuss the future updates? :) And thank you for all your time and contributions :)

**Comment by peacechen** [comment]
v1.2.0 implements responsive sizing. Refer to the Readme for new props `innerStyle`, `maxDayComponentSize`, and `maxDayComponentSize`.

This change is likely to cause slight differences in rendering behavior compared to previous versions.  Please report any issues with the responsive sizing.  If there's a critical bug, downgrade to v1.1.0.

**Comment by peacechen** [comment]
v1.2.1 properly sizes the WeekSelector components.  I missed those changes in the 1.2.0 commit.
