### ISSUE TITLE
Invalid prop `controlDate`

### ISSUE THREAD

**Issue by valmack** [BugiDev/react-native-calendar-strip#140]
The controlDate propType is currently set to `PropTypes.object`

The documentation states in should `PropTypes.any` and based on how it is used (it expects a string so it can be converted to a moment date) it should be any or string.

I don't think this bug breaks anything but its a quick fix and saves a warning.

**Comment by peacechen** [comment]
Thanks @valmack for noticing this.  I pushed your suggested fix and will be included in the next release.
