### ISSUE TITLE
How can i set Arabic language? 

### ISSUE THREAD

**Issue by islamAbuJamea95** [BugiDev/react-native-calendar-strip#141]

**Comment by peacechen** [comment]
This library uses Moment JS to support localization.
https://github.com/BugiDev/react-native-calendar-strip#localization

**Comment by islamabujamea** [comment]
> This library uses Moment JS to support localization.
> https://github.com/BugiDev/react-native-calendar-strip#localization

I tried using localication , I did like :
const locale = {
    name: 'ar',
    config: {
        months: 'كانون الثاني _شباط _آذار_نيسان_أيار_حزيران _تموز_آب_أيلول_تشرين الأول_ تشرين الثاني_كانون الأول'.split('_'),
        weekdays: 'الأحد_الإثنين_الثلاثاء_الأربعاء_الخميس_الجمعة_السبت'.split('_'),
        weekdaysShort: 'ح_ن_ث_ر_خ_ج_س'.split('_'),
    }
};



but when I generate APK the app not working :(

**Comment by peacechen** [comment]
Refer to the solution posted in #110.
