### ISSUE TITLE
Remove borderRadius from selected day

### ISSUE THREAD

**Issue by IronTony** [BugiDev/react-native-calendar-strip#143]
Hi,
really awesome component.
Just a question, is it possibile to use `type: "background"` and remove the `borderRadius` from the selected day, so instead of having a circle I can have a square? How?

Thank you in advance

**Comment by peacechen** [comment]
Try the prop `customDatesStyles`, specifically `dateContainerStyle`.  There's an example in the expandable code block.
https://github.com/BugiDev/react-native-calendar-strip#customdatesstyles

**Comment by IronTony** [comment]
Thank you for the hint.
Just a little remark, if I copy/paste the example in my render there are some errors in the code provided.

**Comment by IronTony** [comment]
It has to be like this:
```
customDatesStyles.push({
        startDate: startDate.clone().add(i, 'days'), // Single date since no endDate provided
        dateNameStyle: styles.dateNameStyle,
        dateNumberStyle: styles.dateNumberStyle,
        // Random color...
        dateContainerStyle: { backgroundColor: `#${(`#00000${(Math.random() * (1 << 24) | 0).toString(16)}`).slice(-6)}` },
      });
```

**Comment by IronTony** [comment]
By the way I proposed a [PR](https://github.com/BugiDev/react-native-calendar-strip/pull/144) to fix it, but thank you for the hint. Now my problem is fixed.
thank you so much and keep going with this awesome package
