### ISSUE TITLE
Marked dates cause dates to not be aligned correctly

### ISSUE THREAD

**Issue by sam1463** [BugiDev/react-native-calendar-strip#148]
When marking some dates using the `markedDates` prop, the dots result in the day names/numbers not being aligned. Is there a way to set the styling for the day list to fix this, or any ideas what I'm doing wrong? See attached screenshot.
<img width="374" alt="Screen Shot 2019-09-29 at 9 59 18 AM" src="https://user-images.githubusercontent.com/8836958/65833605-0f3fe080-e2a0-11e9-9cc8-7c2246d699a3.png">

**Comment by peacechen** [comment]
@hellpirat added this feature in #121 and fixed the vertical alignment in #123.  This could be device specific.  Which phone or tablet are you running on, and does it happen on other models?

**Comment by sam1463** [comment]
@peacechen I'm seeing this behavior running on simulators for the iPhone Xr and iPhone 8. I'm on version 1.3.9. I'm not really using much styling either, just passing a style of `{ height: 92, paddingBottom: 8 }`, and the strip is within a View with style of `{ flex: 1 }`

**Comment by peacechen** [comment]
@hellpirat  Any insight on this?  Did you develop on iOS or Android?

**Comment by JuusoPalander** [comment]
Is there some kind of center align? I guess this could be solved by aligning the days to top for example.

I have this same issue on both Android and iOS.

**Comment by sam1463** [comment]
Yeah I fixed it locally by setting a top align somewhere in their library, but then I ended up not using this library any more since we ended up using a full month view. If I can find time I can open a PR.

**Comment by peacechen** [comment]
That would be great @sam1463 .  I'm not actively working on this and don't have time to fix it.  I'll merge and publish right away when a PR is submitted.

**Comment by sam1463** [comment]
@JuusoPalander see #150

**Comment by lingeshwaran1912** [comment]
@sam1463 I am unable to clear the issue. Please send the screenshot of the sample code.

**Comment by peacechen** [comment]
Fixed in 1.4.0
