### ISSUE TITLE
Date difficult to select

### ISSUE THREAD

**Issue by peacechen** [BugiDev/react-native-calendar-strip#15]
The date is difficult to select using finger touch.  It feels like as though it's missing touches.  After investigation, I've found that the hitbox is on the text instead of its container.  The touch must happen exactly on the text otherwise it won't select.  The solution is simple, swap the TouchableOpacity and Animated wrappers.

I'll submit a PR for this.

**Comment by peacechen** [comment]
Submitted PR #16 to fix this.

**Comment by BugiDev** [comment]
@peacechen PR merged. Thank you!
