### ISSUE TITLE
iOS release version crash on locale (custom language)

### ISSUE THREAD

**Issue by SletmarKets** [BugiDev/react-native-calendar-strip#152]
RN version: 0.60.5
iOS version: 12.2
react-native-calendar-strip version: 1.3.9

Today I'm trying to deploy my application to a release version on a physical device (iPhone 8). In the simulator and the debug version everything works fine, but as soon as I run the release version, the app crashes when I open the page with the calendar strip. 
I installed RayGun as I wasn't getting any error messages on the release build and it told me this: 
<img width="569" alt="Screenshot 2019-10-25 at 16 15 34" src="https://user-images.githubusercontent.com/43061355/67578426-b64e5580-f742-11e9-9ce2-c18667f4ac93.png">
Remembering I added the Dutch language to the calenderstrip I tried to uncomment the custom language, this fixes the problem. But I really need the Dutch language as all the other UI language is in Dutch. The way I implement the custom language is as follow: 
![Screenshot 2019-10-25 at 16 18 03](https://user-images.githubusercontent.com/43061355/67578599-147b3880-f743-11e9-9d29-594311e1e48c.png)
The c. stands for a constants file where all the constants are stored. locale in this constants file looks like this: 

// Dutch language for calendarstrip
export const language = "nl";
export const weekCalendarConfig = { 
    months: "Januari_Februari_Maart_April_Mei_Juni_Juli_Augustus_September_Oktober_November_December".split('_'),
    monthsShort: "Jan_Feb_Mrt_Apr_Mei_Jun_Jul_Aug_Sept_Okt_Nov_Dec".split("_"),
    weekdays: "Zondag_Maandag_Dinsdag_Woensdag_Donderdag_Vrijdag_Zaterdag".split("_"),
    weekdaysShort: "Zo_Ma_Di_Woe_Do_Vr_Za".split("_"),
    weekdaysMin: "Zo_Ma_Di_Woe_Do_Vr_Za".split('_'),
    longDateFormat: {
        LT: "HH:mm",
        LTS: "HH:mm:ss",
        L: "DD/MM/YYYY",
        LL: "D MMMM YYYY",
        LLL: "D MMMM YYYY LT",
        LLLL: "dddd D MMMM YYYY LT"
    },
    calendar: {
        sameDay: "[Vandaag] LT",
        nextDay: "[Morgen] LT",
        nextWeek: "dddd [om] LT",
        lastDay: "[Gisteren om] LT",
        lastWeek: "dddd [duurt tot] LT",
        sameElse: "L"
    },
    relativeTime: {
        future: "over %s",
        past: "er is %s",
        s: "enkele seconden",
        m: "een minuut",
        mm: "%d minuten",
        h: "een uur",
        hh: "%d uren",
        d: "een dag",
        dd: "%d dagen",
        M: "een maand",
        MM: "%d maanden",
        y: "een jaar",
        yy: "%d jaren"
    },
    ordinalParse: /\d{1,2}(er|ème)/,
    ordinal: function(number: number) {
      return number + (number === 1 ? "er" : "ème");
    },
    meridiemParse: /PD|MD/,
    isPM: function(input: string) {
      return input.charAt(0) === "M";
    },
    // in case the meridiem units are not separated around 12, then implement
    // this function (look at locale/id.js for an example)
    // meridiemHour : function (hour, meridiem) {
    //     return /* 0-23 hour, given meridiem token and hour 1-12 */
    // },
    meridiem: function(hours: number, minutes: number, isLower: number) {
        return hours < 12 ? "PD" : "MD";
    },
    week: {
        dow: 1, // Monday is the first day of the week.
        doy: 4 // The week that contains Jan 4th is the first week of the year.
    }
};
export const locale = { name: language, config: weekCalendarConfig }

Like I said, in the simulator and the debug mode everything worked fine, only the release version crashes. Hopefully anyone is able to help me or push me in the right direction as I have no idea what could cause this problem. Many thanks in advance!

**Comment by johnromulo** [comment]
Olá, também ocorreu  esse problema no meu projeto.

Minha solução: 
1- importe o módulo do momentJs: 
$ yarn  add moment 

2- Va para seu index.js e import o "Locale" especifico
ex: import 'moment/locale/pt-br';

Funcionou para mim :),

**Comment by johnromulo** [comment]
Hello, this problem also occurred in my project.

My solution:
1- import momentJs module:
$ yarn add moment

2- Go to your index.js and import the specific "Locale"
ex: import 'moment / locale / en';

It worked for me :)

**Comment by peacechen** [comment]
Thanks @johnromulo for sharing your solution.  This was also the solution posted in #110.

**Comment by SletmarKets** [comment]
Thanks @johnromulo! This indeed was the solution for my problem.
Thanks you @peacechen for the link to another solution, I should of searched a little bit better.

**Comment by peacechen** [comment]
np.  The Readme should be updated to make this clearer.  Would anyone mind submitting a PR? 😄

**Comment by johnromulo** [comment]
Yes, created  this link [153](https://github.com/BugiDev/react-native-calendar-strip/pull/153)

**Comment by longpq18** [comment]
only work on debug, release not work

**Comment by peacechen** [comment]
Did you follow the instructions in the Readme that john added?  Post your project code including all the imports at the top.

**Comment by longpq18** [comment]
@peacechen my code
> import React, { memo } from 'react';
import CalendarStrip from "react-native-calendar-strip";
import { Images } from 'assets';
import styles from './styles';

import 'moment';
import 'moment/locale/vi';
import moment from 'moment-timezone'

const locale = {
  name: moment().locale('vi'),
  config: {
    months: 'Tháng 1_Tháng 2_Tháng 3_Tháng 4_Tháng 5_Tháng 6_Tháng 7_Tháng 8_Tháng 9_Tháng 10_Tháng 11_Tháng 12'.split(
      '_'
    ),
    monthsShort: 'Tháng 1_Tháng 2_Tháng 3_Tháng 4_Tháng 5_Tháng 6_Tháng 7_Tháng 8_Tháng 9_Tháng 10_Tháng 11_Tháng 12'.split(
      '_'
    ),
    weekdays: 'CN_T2_T3_T4_T5_T6_T7'.split('_'),
    weekdaysShort: 'CN_T2_T3_T4_T5_T6_T7'.split('_'),
    weekdaysMin: 'CN_T2_T3_T4_T5_T6_T7'.split('_'),
    week: {
      dow: 1,
      doy: 4
    }
  }
};

const WeekCalendar = ({
  onWeekChanged,
  onDateSelected,
}) => {
  return (
    <CalendarStrip
      style={styles.container}
      calendarHeaderStyle={styles.textHeader}
      calendarColor={'#73C6B6'}
      dateNumberStyle={{ color: 'white', fontSize: 13 }}
      dateNameStyle={{ color: 'white', fontSize: 10 }}
      iconLeft={Images.leftArrowIcon}
      iconRight={Images.rightArrowIcon}
      iconContainer={{ flex: 0.1 }}
      locale={locale}
      onWeekChanged={onWeekChanged}
      onDateSelected={onDateSelected}
    />
  );
}

export default memo(WeekCalendar)

**Comment by ErkanGorgulu** [comment]
Hi, I have encountered this problem now. I am using an android phone and also Android Studio Emulator. Both have this problem on published expo projects. Is there any way that I can fix this within App.js using Expo?

**Comment by peacechen** [comment]
Did you follow the instructions in the Readme for localization?
https://github.com/BugiDev/react-native-calendar-strip#localization

**Comment by ErkanGorgulu** [comment]
My mistake. You could actually do that in app.js in expo too. I just didn't notice to import moment first. Thank you.
