### ISSUE TITLE
Invalid props.style key `color` supplied to `Image`

### ISSUE THREAD

**Issue by djohnsonkc** [BugiDev/react-native-calendar-strip#154]
Hi,

Thanks for a great component. In using RN 0.60+, and version 1.3.9 of the react-native-calendar-strip, I'm seeing this warning message. 

Warning: Failed prop type: Invalid props.style key `color` supplied to `Image`.
in Image (at WeekSelector.js:85)

Thanks!

**Comment by peacechen** [comment]
The primary style props passed down to `WeekSelector` are iconInstanceStyle and iconStyle.  Those props have no defaults, and the built-in styles don't have color for the left/right selector components.  Would you post your `<CalendarStrip>` code along with all the styles passed to it?

**Comment by djohnsonkc** [comment]
Thanks for the reply. After looking more closely, I saw that I had an iconStyle={ color } attribute for some reason with some earlier experimentation. I removed that and the warning went away. Thanks again for a very nice component.
