### ISSUE TITLE
onDateSelected()  return  wrong date if not set delay

### ISSUE THREAD

**Issue by spinater** [BugiDev/react-native-calendar-strip#155]
if not set little delay ( only 1 is enought ) when onDateSelected() is return wrong date time 

this is my code that can fix issue
     setTimeout(() => {
            this.setState({
                textSelectedDate: moment.utc(this.dateSelector.getSelectedDate())
            },
                () => {
                    console.log("DATE :", this.state.textSelectedDate)
                })
        }, 1);

and this code return wrong date time 

      this.setState({
                textSelectedDate: moment.utc(this.dateSelector.getSelectedDate())
            },
                () => {
                    console.log("DATE :", this.state.textSelectedDate)
                })

Thank.

**Comment by peacechen** [comment]
The `onDateSelected()` callback returns the selected date in the first parameter.  Are you using that value?  Please post your `<CalendarStrip>` code usage and the callbacks passed to it.

**Comment by spinater** [comment]
> The `onDateSelected()` callback returns the selected date in the first parameter. Are you using that value? Please post your `<CalendarStrip>` code usage and the callbacks passed to it.

 <CalendarStrip
                                ref={component => this.dateSelector = component}
                                calendarAnimation={{ type: 'Sequence', duration: 100 }}
                                daySelectionAnimation={{
                                    type: 'border',
                                    duration: 100,
                                    borderWidth: 3,
                                    borderHighlightColor: '#EB1557',
                                }}
                                calendarHeaderStyle={{ color: 'white' }}
                                calendarColor={'#00345D'}
                                highlightDateNumberStyle={{ color: '#EB1557' }}
                                highlightDateNameStyle={{ color: '#EB1557', fontWeight: 'bold' }}
                                disabledDateNameStyle={{ color: 'grey' }}
                                disabledDateNumberStyle={{ color: 'grey' }}
                                dateNumberStyle={{ color: 'white' }}
                                dateNameStyle={{ color: 'white' }}
                                borderHighlightColor={'#9265DC'}
                                style={styles.boarder}
                                datesWhitelist={this.state.datesWhitelist}
                                datesBlacklist={datesBlacklist}
                                iconStyle={{ overlayColor: '#EB1557' }}
                                iconLeft={require('./assets/chevron_left.png')}
                                iconRight={require('./assets/chevron_right.png')}
                                onDateSelected={() => this.onDateSelected()}
     />
________________________________
    onDateSelected = () => {

        setTimeout(() => {
            this.setState({
                textSelectedDate: this.dateSelector.getSelectedDate()
            },
                () => {
                    console.log('date selected :' + moment(this.state.textSelectedDate).format('DD-MM-YYYY'))
                    this.getTimeSlot(moment(this.state.textSelectedDate).format('DD-MM-YYYY'))
                })
        }, 1);
    }

**Comment by peacechen** [comment]
That's not the optimal way to use it.  Use the first argument provided to the callback.  Ex:
```

onDateSelected = selectedDate => {
    this.setState({
        textSelectedDate: selectedDate
    });
    console.log('date selected :' + moment(this.state.textSelectedDate).format('DD-MM-YYYY'));
    this.getTimeSlot(moment(this.state.textSelectedDate).format('DD-MM-YYYY'));
}```

**Comment by spinater** [comment]
> That's not the optimal way to use it. Use the first argument provided to the callback. Ex:
> 
> ```
> 
> onDateSelected = selectedDate => {
>     this.setState({
>         textSelectedDate: selectedDate
>     });
>     console.log('date selected :' + moment(this.state.textSelectedDate).format('DD-MM-YYYY'));
>     this.getTimeSlot(moment(this.state.textSelectedDate).format('DD-MM-YYYY'));
> }
> ```

Thank you sir

**Comment by peacechen** [comment]
You're welcome.  There's a bug in the code snippet I provided.  `setState()` takes time to update state, so the lines following it should reference `selectedDate` instead of `this.state.textSelectedDate`.  You could also put those lines as a callback function to setState, but that's unnecessary unless you have other reasons to wait for the state to update.
