### ISSUE TITLE
Swipeable feature inquiry

### ISSUE THREAD

**Issue by Wmeng98** [BugiDev/react-native-calendar-strip#159]
Just wanted to say that i'm loving this component!

I noticed a branch named swipeable. Is the feature implemented and working on this branch?

Thanks :)

**Comment by dl-husky73** [comment]
Did you ever get an answer on swipeable component?   I really like this calendar strip but it really needs swipe action.

**Comment by peacechen** [comment]
IIRC I made that branch for contributors to work off of.  No one came forward with a working swipe solution.  There are RN gesture libraries that would help implement this better and hopefully faster than with the built in RN methods.  This is a community supported library and depends on contributors to help implement new features.  Please consider submitting a PR.

**Comment by peacechen** [comment]
This has been published in the 2.0.0 release.

Please open a new issue if you find bugs.
