### ISSUE TITLE
[Question] is it possible to hide left and right arrows?

### ISSUE THREAD

**Issue by rikinshah23** [BugiDev/react-native-calendar-strip#172]
Hello,
Thanks for this great working package. 
We want a control which shows only current week and not let user to switch week using those arrows. 

is it possible to hide left and right arrows at moment ? or any workaround? 

Thanks

**Comment by peacechen** [comment]
Yes, use the `leftSelector` and `rightSelector` props.
https://github.com/BugiDev/react-native-calendar-strip#icon-sizing
