### ISSUE TITLE
how do i show the current day in the middle of the strip, instead of the whole week startin from monday

### ISSUE THREAD

**Issue by Vasault** [BugiDev/react-native-calendar-strip#179]
i guess the title says pretty much everything, i want to show the current day, let's say moment() and let's pretend is friday, so instead of showing monday to sunday, show tuesday to monday.

**Comment by peacechen** [comment]
The `startingDate` prop can do that.
https://github.com/BugiDev/react-native-calendar-strip#initial-data-and-ondateselected-handler

**Comment by Vasault** [comment]
how do i offset the calendar if possible? i mean, i already set the current day to always be selected, but still have no clue to do the rest, got the same issue with rn calendar agenda

**Comment by geraldo-thorpe-innovation** [comment]
I also have the same problem

**Comment by peacechen** [comment]
Re-reading the documentation, the `useIsoWeekday ` prop should also be set to false.
> useIsoWeekday | start week on ISO day of week (default true). If false, starts week on startingDate parameter.

Example:
```
        startingDate={moment().add(1, 'day')}
        useIsoWeekday={false}
```

**Comment by Vasault** [comment]
i love you xd yep, that's exactly what we needed

            minDate={moment().subtract(3, 'days')}
            maxDate={moment().add(3,'days')}
            startingDate={moment().subtract(3, 'days')}
            useIsoWeekday={false}
