### ISSUE TITLE
onNext/onPrev props

### ISSUE THREAD

**Issue by amhinson** [BugiDev/react-native-calendar-strip#18]
I'm finding myself needing to call a function when the 'previous' or 'next' buttons are pressed. I currently don't see any way to hook into that, but maybe I am missing something?

UPDATE:
Looks like there is a PR for this out right now.
https://github.com/BugiDev/react-native-calendar-strip/pull/17

**Comment by BugiDev** [comment]
@amhinson The PR has been merged and you can find this in the release v0.1.3
