### ISSUE TITLE
Callback on calendar header month

### ISSUE THREAD

**Issue by rdewolff** [BugiDev/react-native-calendar-strip#182]
Is there a way to add a callback on the calendar header, the displayed Month? That'd be great to allow us to add some features like showing a calendar to jump to a specific date.

**Comment by peacechen** [comment]
That's certainly possible by wrapping the header in a TouchableOpacity.  Would you be interested in submitting a PR?

**Comment by peacechen** [comment]
Prop `onHeaderSelected` added in 2.0.3
