### ISSUE TITLE
Some problem about setSelectedDate() and updateWeekView()

### ISSUE THREAD

**Issue by jessehsiao** [BugiDev/react-native-calendar-strip#187]
Hello I'm a rookie in react native, I tried  to use the TouchableOpacity to navigate to Calendar List.js
in calendarStrip.js:

`              <TouchableOpacity onPress={()=>{navigation.navigate('Calendar List',{onGoBack: this.returnData,})}} style={styles.button1Style}>     
                  <Text></Text>  
              </TouchableOpacity>  `

It will navigate to CalendarList.js and then i wish to select the date to change the calendar strip

CalendarList.js:
`          onDayPress={(months) => {
            const selectedDate = months.dateString;
            this.props.route.params.onGoBack(selectedDate);
            this.props.navigation.navigate('calendarStrip');
          }}`

it is able to pass the date back to calendarStrip.js:

`    returnData=(date)=>{ 
      //console.log('back: ',date)
      this.calendarRef.updateWeekView(date);
      this.calendarRef.setSelectedDate(date);
    }`

However there is a problem:

![problem](https://user-images.githubusercontent.com/60601231/83128788-7dc68e00-a10e-11ea-82df-b1825e459c0b.gif)

I open the calendar List and selected June 3th, but the week view in calendar strip didn't change before I press right icon and press left icon back, I'm wondering what happen@@?

**Comment by peacechen** [comment]
This is difficult to debug without your code.  Please create a [Snack ](https://snack.expo.io/) that recreates the behavior.

**Comment by jessehsiao** [comment]
Here is my code: https://snack.expo.io/@jessehsiao/react-calendar

**Comment by peacechen** [comment]
I fixed some errors in your snack.  `react-native-calendar-strip` needed to be added to package.json.  NewAppScreen was undefined and not used, so I removed it. 

It runs now and I can see the CalendarStrip.  Clicking on a date doesn't show the full calendar.

**Comment by jessehsiao** [comment]
I finally solved it! I followed your instruction and fixed my code like this: https://snack.expo.io/@jessehsiao/react-calendar

Thanks for your advise, I will keep working hard!

**Comment by peacechen** [comment]
Glad that you got it working.  You should be able to remove the imperative calls to `updateWeekView` and `setSelectedDate` by also setting the `startingDate` prop to the same date as `selectedDate` state.
