### ISSUE TITLE
Feature: Add underline mark to dates

### ISSUE THREAD

**Issue by Vasault** [BugiDev/react-native-calendar-strip#190]
i've been trying several ways to make this, and at this point i'm not entirely sure if is possible

<img width="490" alt="Captura de Pantalla 2020-05-29 a la(s) 12 23 05" src="https://user-images.githubusercontent.com/15862547/83441527-aacbb700-a414-11ea-8f44-60faf1da5c05.png">

the line below the day, and the shadow below the container

**Comment by peacechen** [comment]
A new/enhanced prop would be required to add that feature.  `markedDates` is a similar prop that could be extended to support underlining.  It should be a relatively straight-forward change to add underlining to `markedDates`.
This is a community supported library and your contributions are welcome.  Please submit a PR and I'll review promptly.

**Comment by peacechen** [comment]
The underline feature has been added to the master branch.  You have the option to pass an array or callback to `markedDates`.
https://github.com/BugiDev/react-native-calendar-strip#markeddates-example

Until a new version is published, point to this repo directly in `package.json`.  Run `npm install` after changing it.
```
  "dependencies": {
    "react-native-calendar-strip": "https://github.com/BugiDev/react-native-calendar-strip",
    ...
  }
```

**Comment by Vasault** [comment]
thank you peacechen
