### ISSUE TITLE
Bug with scrollable prop active on iOS devices

### ISSUE THREAD

**Issue by caiobiodere** [BugiDev/react-native-calendar-strip#192]
there is a bug that seems to be happening only on iOS devices, while scrolling I could see the label blinking and almost like it is disappearing from the container view. Is there any workaround/solution available to get this working properly?
![simulator](https://user-images.githubusercontent.com/1935649/83715410-609b3d80-a681-11ea-98c5-1eded3ba51a1.gif)

**Comment by peacechen** [comment]
I've observed that on an iPad as well.  Which device(s) did you test on?

Here's a video of it on the iPad:
https://www.youtube.com/watch?v=E_4LvwLXMh4

This library uses [RecyclerListView](https://github.com/Flipkart/recyclerlistview) to implement the bidirectional infinite scroller.  RecyclerListView works by recycling components from the non-visible end to the visible end that the scroller moves toward.  The shifts should be instantaneous and invisible, but there's a bug or limitation in RecyclerListView.  If you have time, it would be of great help to try to debug that in RecyclerListView.

**Comment by caiobiodere** [comment]
I was testing on an iPhone 11 but could see the problem happening in any iOS devices, because I am using this plugin in a company project might be worth trying to fix this problem will see what I can do mate.

**Comment by caiobiodere** [comment]
@peacechen hey mate I found what was happening, it was a small thing just because it wasn't checking if scrollable prop was either active or not it was still creating and updating day selection animation on componentDidUpdate method, could you please approve this pull request:

https://github.com/BugiDev/react-native-calendar-strip/pull/193

**Comment by peacechen** [comment]
Great detective work @caiobiodere  👍   Your help is much appreciated.

The fix has been published in 2.0.3
