### ISSUE TITLE
App crashes due to RecyclerListView needs to have a bounded size

### ISSUE THREAD

**Issue by VanessaChu** [BugiDev/react-native-calendar-strip#207]
I am receiving this crash with the following error when setting scrollable to true. When set to false, it does not crash.

RecyclerListView needs to have a bounded size. Currently height or, width is 0.Consider adding style={{flex:1}} or, fixed dimensions Code=1 

```
<View style={{ flex: 1 }} w>
                <CalendarStrip
                    scrollable
                    style={{ height: 100, width: '100%', backgroundColor: COLOR.SQUID_INK }}
                    showMonth={false}
                    maxDate={moment()}
                    minDate={moment().subtract(28, 'days')}
                    selectedDate={selectedDate}
                    onDateSelected={this.onDateSelected}
                />
            </View>
```

**Comment by peacechen** [comment]
I tested your props in the example project in this repo and it works.  Please create a [Snack](https://snack.expo.io/) or upload a minimally reproducible repo that recreates the error.

Something to try first is remove the `width: '100%'` prop.

**Comment by peacechen** [comment]
I saw you posted another issue related to responsive resize bouncing.  If you were able to get past this issue. please share your findings so others can benefit from it.

**Comment by paragspacetotech** [comment]
it's happning with me when i use showMonth={true}
