### ISSUE TITLE
Typescript linting errors in index.d.ts

### ISSUE THREAD

**Issue by subrapak** [BugiDev/react-native-calendar-strip#214]
![](https://cdn.discordapp.com/attachments/724625670927417468/737356628218609813/unknown.png)

**Comment by subrapak** [comment]
When running `yarn test` with v 2.0.8, typescript throws up errors for multiple props to be passed into CalendarStrip. Disabling linting and/or typescript checks for the file doesn't seem to be effective. Issue was finally solved by reverting the package version to 2.0.5.

(NB: changed versions in package.json file, deleted node modules folder and reinstalled all packages. Set to not upgrade version. In package.json:
`"dependencies": {
    ...
   "react-native-calendar-strip": "2.0.5",
   ...
}

**Comment by peacechen** [comment]
Thanks for reporting this.  Would you submit a PR to fix the TS definitions?
