### ISSUE TITLE
paging={true}?

### ISSUE THREAD

**Issue by jawwad22** [BugiDev/react-native-calendar-strip#215]
Hi,Need to enable paging, when scrollable=true in calendar, I want to make swipeable but as paging

**Comment by peacechen** [comment]
Would you provide more details on what you need?  Do you want to swipe to change weeks, but not have the days scroll?  That would be a significant change in design and behavior.  Please submit a PR which adds that feature.

**Comment by jawwad22** [comment]
hi, logic is simple when i give scrollable={true}, its scroll perfectly, now what i want is that, it should scroll in a SET of 7 days, in one swipe,7 previous or next week days show,

**Comment by peacechen** [comment]
Thanks for the explanation.  That could be done by grouping the days into units of 7 and passing them to the RecyclerListView.  It's not a trivial change and it be a while until I can work on it.  If you would like to give it a try, fork this repo and submit a PR.

**Comment by jawwad22** [comment]
ohk, ill give it a try, i hope i could achieved it,

**Comment by jawwad22** [comment]
Hi, man unable to achieve it, can you take a look and help me??

**Comment by prankymat** [comment]
this would be very nice indeed, i'm also interested in this feature.

**Comment by prankymat** [comment]
it seems like recyclerlistview has a property for PagingEnabled. I've tried adding it in and it seem to work out of the box.

[](https://github.com/Flipkart/recyclerlistview/issues/240)

**Comment by peacechen** [comment]
Thanks @prankymat for the news about that prop. Would you mind adding a new prop `scrollerPaging` that gets passed through to RLV as its `paging` prop?  That new prop will need to be added to the Readme and TS definitions.

**Comment by prankymat** [comment]
sure thing! Will make a PR.

**Comment by prankymat** [comment]
just realized that `pagingEnabled` will cause some layout issue, instead using `snapToInterval` with `decelerationRate` seems more promising.

**Comment by peacechen** [comment]
Released in 2.1.4
