### ISSUE TITLE
access getSelectedDate()

### ISSUE THREAD

**Issue by sabirsalah1** [BugiDev/react-native-calendar-strip#217]
Hi, I'm kind of new to react Native and I'm trying to access getSelectedDate() so that I can get the currently selected date returned to me. can anyone give me an example of how I can access this method?

**Comment by peacechen** [comment]
`onDateSelected` is recommended over synchronously getting the selected date.
https://github.com/BugiDev/react-native-calendar-strip#initial-data-and-ondateselected-handler

**Comment by sabirsalah1** [comment]
how would you access the function?

**Comment by peacechen** [comment]
Refer to the example app in this repo.
https://github.com/BugiDev/react-native-calendar-strip/blob/1214514fdbdc08ac326889a40c9c094237bd693b/example/App.js#L66
