### ISSUE TITLE
how to set dateContainerStyle in calendarStrip

### ISSUE THREAD

**Issue by arulmuthunas** [BugiDev/react-native-calendar-strip#218]
![Screenshot 2020-08-06 at 1 34 19 PM](https://user-images.githubusercontent.com/42431888/89508301-5d404180-d7eb-11ea-88b5-340dce8ae441.png)
this is my current calendarStrip modal
![Screenshot 2020-08-06 at 1 34 31 PM](https://user-images.githubusercontent.com/42431888/89508337-6af5c700-d7eb-11ea-9ff1-488c2d6ceecf.png)
but i want like this border radius

**Comment by herksaw** [comment]
Been searching for ways to achieve this, without modifying underlying source code.

**Comment by Vasault** [comment]
same here and is urgent :( , mostly looking for the month, year header to be align on the left

**Comment by peacechen** [comment]
Try `calendarHeaderContainerStyle` for the month & year container.


I have added the prop `dayContainerStyle` in commit 0f49b5b2fb602e55014760a682a3d54a3175192e. Here's an example of how to make it a rounded rectangle:
```
        <CalendarStrip
          dayContainerStyle={{borderRadius: 10}}
        />
```

**Comment by peacechen** [comment]
Published in 2.1.2

**Comment by QuintonC** [comment]
@peacechen Can we get `dayContainerStyle` added to the types definitions?

**Comment by peacechen** [comment]
@QuintonC 
Thanks for your PR. I haven't had time to fix & test this component, but I will review and merge PRs as soon as I can.
