### ISSUE TITLE
Ref typings not recognized in IDE Typescript

### ISSUE THREAD

**Issue by AjitZK** [BugiDev/react-native-calendar-strip#220]
My IDE, Webstorm, still can't recognize the typings even though I have checked that my version includes the fix from #169 

![image](https://user-images.githubusercontent.com/40203625/89518488-8a9de700-d80d-11ea-90c3-81c23852c376.png)

Error shown is:
```
TS2339: Property 'getPreviousWeek' does not exist on type 'ReactNativeCalendarStrip'.
```

_Originally posted by @AjitZK in https://github.com/BugiDev/react-native-calendar-strip/issues/168#issuecomment-669224950_

**Comment by peacechen** [comment]
A number of Typescript issued have been fixed in 2.1.0.  Please try that out and if there are any more, report them here or in a new issue.
