### ISSUE TITLE
custom keyboard in react native

### ISSUE THREAD

**Issue by arulmuthunas** [BugiDev/react-native-calendar-strip#221]
![Screenshot 2020-08-12 at 8 56 23 AM](https://user-images.githubusercontent.com/42431888/89971756-bab81080-dc79-11ea-83c1-4135b57c515b.png)
PLEASE TELL ME how to create like this its very tough to print number in textinput

**Comment by peacechen** [comment]
It looks like you posted to the wrong repo

**Comment by Josefpa** [comment]
Did You Find an Answer?

**Comment by IvanFestina** [comment]
Please, if you found an answer, share it!
