### ISSUE TITLE
How to update selected date when value of prop selectedDate has changed?

### ISSUE THREAD

**Issue by auliakbarh** [BugiDev/react-native-calendar-strip#226]
How to update selected date when value of prop selectedDate has changed?

case:
I have a screen using <CalendarStrip />, a button and dateValue state.
<CalendarStrip selectedDate={dateValue} ...  />
my button changed the dateValue state, but component <CalendarStrip /> doesn't updated.

**Comment by peacechen** [comment]
The `selectedDate` prop may need to be added to the prop change detection. Would you mind submitting a PR?
https://github.com/BugiDev/react-native-calendar-strip/blob/master/src/CalendarStrip.js#L145

**Comment by peacechen** [comment]
This has been fixed in 9cd6ab74ee37fc0884a14576a4e77524356dc501 and will be in the next release.
