### ISSUE TITLE
how to center pre-selected date in calendar strip?

### ISSUE THREAD

**Issue by VanessaChu** [BugiDev/react-native-calendar-strip#229]
Given that we have set a min and max date, how can we center the pre-selected date in the center of the calendar strip?

Currently, when we first load the calendar strip, the selected date appears on the left. 
https://www.amazon.com/photos/shared/JuVIRcO9Sqapjy_jJc86PA.c1XBWpf4jmgCk4OZm98IjO
What I want to configure is to have the the selected date centered on the strip on first load
https://www.amazon.com/photos/shared/DO_KzZv7RWi4QfNd9lvC7A.3sITIXJhPcdoJiyOihFQ_B

**Comment by peacechen** [comment]
Set `startingDate` offset such that the selectedDate is centered (e.g. if you want Thursday centered, the startingDate should be on a Tuesday). Also set `useIsoWeekday` false.
https://github.com/BugiDev/react-native-calendar-strip#props

**Comment by VanessaChu** [comment]
That didn't work with scrollable set to true
