### ISSUE TITLE
Crash on initialisation when CPU is stress

### ISSUE THREAD

**Issue by cc-matthias-m** [BugiDev/react-native-calendar-strip#236]
Hello everyone,

We discovered a problem on initialization when the CPU usage is high.

This bug come from production on old phone or when too many application are launched. To reproduce this bug in development easily, we need to stress the CPU.

This is what you see with this bug (the calendar will display on the bottom of the screen) :
![calendar](https://user-images.githubusercontent.com/66009541/99658591-ff64fc00-2a5f-11eb-8cd0-5a78fdef8493.gif)

With analyses, we discover that this error happen when `visibleStartIndex` is `undefined` because the component `RecyclerListView` has not been initialize yet.

I will make a PR to patch the problem.

**Comment by peacechen** [comment]
The fix has been published in 2.1.0
