### ISSUE TITLE
Date disappear when selected on android

### ISSUE THREAD

**Issue by safwentrabelsi** [BugiDev/react-native-calendar-strip#238]
Date disappear when selected on android
![126860407_762164497702148_3410939019826670620_n](https://user-images.githubusercontent.com/26767006/99908581-c76deb00-2ce3-11eb-8aeb-bb3c2c442b15.jpg)

```
<CalendarStrip
          scrollable
          style={styles.calendar}
          showMonth={false}
          calendarColor={'#FFFFFF'}
          calendarHeaderStyle={{color: 'black'}}
          dateNumberStyle={{color: 'black'}}
          dateNameStyle={{color: 'black'}}
          iconContainer={{flex: 0.1}}
          daySelectionAnimation={{
            type: 'background',

            highlightColor: '#d3d3d3',
          }}
          selectedDate={selectedDate}
          onDateSelected={this.onDateSelected}
          markedDates={date => {
            if (date.dayOfYear() === moment().dayOfYear()) {
              return {
                dots: [
                  {
                    color: 'black',
                  },
                ],
              };
            }
          }}
        />
```

**Comment by josue-castro** [comment]
Im using react-native with expo and I just noticed I have this same issue on android. I need some quick fixing for school project

**Comment by gaurav0044** [comment]
> Date disappear when selected on android
> ![126860407_762164497702148_3410939019826670620_n](https://user-images.githubusercontent.com/26767006/99908581-c76deb00-2ce3-11eb-8aeb-bb3c2c442b15.jpg)
> 
> ```
> <CalendarStrip
>           scrollable
>           style={styles.calendar}
>           showMonth={false}
>           calendarColor={'#FFFFFF'}
>           calendarHeaderStyle={{color: 'black'}}
>           dateNumberStyle={{color: 'black'}}
>           dateNameStyle={{color: 'black'}}
>           iconContainer={{flex: 0.1}}
>           daySelectionAnimation={{
>             type: 'background',
> 
>             highlightColor: '#d3d3d3',
>           }}
>           selectedDate={selectedDate}
>           onDateSelected={this.onDateSelected}
>           markedDates={date => {
>             if (date.dayOfYear() === moment().dayOfYear()) {
>               return {
>                 dots: [
>                   {
>                     color: 'black',
>                   },
>                 ],
>               };
>             }
>           }}
>         />
> ```

same problem

**Comment by josue-castro** [comment]
> Im using react-native with expo and I just noticed I have this same issue on android. I need some quick fixing for school project. When I select a date it disappears but then if I select another the previous one is visible again.
> 
> I even set the following props in case the default highlight was white, but it did not work. My calendar background color is white.
> highlightDateNameStyle={'black'}
> highlightDateNumberStyle={'black'}

Well for some reason I just tried this again and it work. If your calendar color is white make sure to set a highlightDateNameStyle color. Try their expo snack and you can see it works on android. They have blue background and yellow on highlightDateNameStyle. Hope is not something that sometimes work and sometimes doesnt

**Comment by gaurav0044** [comment]
> > Im using react-native with expo and I just noticed I have this same issue on android. I need some quick fixing for school project. When I select a date it disappears but then if I select another the previous one is visible again.
> > I even set the following props in case the default highlight was white, but it did not work. My calendar background color is white.
> > highlightDateNameStyle={'black'}
> > highlightDateNumberStyle={'black'}
> 
> Well for some reason I just tried this again and it work. If your calendar color is white make sure to set a highlightDateNameStyle color. Try their expo snack and you can see it works on android. They have blue background and yellow on highlightDateNameStyle. Hope is not something that sometimes work and sometimes doesnt

still it's not working , when i select date then it will disappear  whether it's white color or any other color. but anyways i created my own calander stipe component now.

**Comment by gaurav0044** [comment]
> > > Im using react-native with expo and I just noticed I have this same issue on android. I need some quick fixing for school project. When I select a date it disappears but then if I select another the previous one is visible again.
> > > I even set the following props in case the default highlight was white, but it did not work. My calendar background color is white.
> > > highlightDateNameStyle={'black'}
> > > highlightDateNumberStyle={'black'}
> > 
> > 
> > Well for some reason I just tried this again and it work. If your calendar color is white make sure to set a highlightDateNameStyle color. Try their expo snack and you can see it works on android. They have blue background and yellow on highlightDateNameStyle. Hope is not something that sometimes work and sometimes doesnt
> 
> still it's not working , when i select date then it will disappear whether it's white color or any other color. but anyways i created my own calander stripe component now.


and i hope this issue will solve soon.

**Comment by ganesh-papola** [comment]
@gaurav0044 any solutions?

**Comment by peacechen** [comment]
The example project in this repo uses Expo and date selection works properly. Check that your code is updating its local state correctly.
https://github.com/BugiDev/react-native-calendar-strip/tree/master/example

Instructions to get the example running:
https://github.com/BugiDev/react-native-calendar-strip#development-with-sample-application

**Comment by HassanHaiderIX** [comment]
> @gaurav0044 any solutions?
try adding this so that date changes back to original color once it is unselected
 dateNameStyle={{color: 'black'}}
 dateNumberStyle={{color: 'black'}}
