### ISSUE TITLE
If scrollable then setSelectedDate is not centering calendar

### ISSUE THREAD

**Issue by majugurci** [BugiDev/react-native-calendar-strip#240]
If the scrollable property is set to true, method setSelectedDate will not reposition calendar so that selected date is in the view.

I have made 2 snacks which replicate this. When you click the button bellow the calendar it sets the new date. But if scrollable={true} then it wont reposition the calendar.

[Snack with scrollable](https://snack.expo.io/@mjugurcic/rncs---scrollable-bug)

[Snack without scrollable](https://snack.expo.io/@mjugurcic/rncs---without-scrollable)

**Comment by wroxer** [comment]
same here

**Comment by peacechen** [comment]
Yes that is a bug in the scroller. PR #247 adds a `scrollToDate` method to the scroller that can be leveraged for this. Once that's merged, it should be simple to call that in `setSelectedDate()`

**Comment by peacechen** [comment]
Published in 2.1.1
Happy New Year 🎆

**Comment by majugurci** [comment]
Thank you, I have tested it and it works good now.
