### ISSUE TITLE
updateWeekView does not work with scrollable calendar strip

### ISSUE THREAD

**Issue by JeriesNasrawi** [BugiDev/react-native-calendar-strip#241]
In a scrollable calendar strip, updating week view does not work. You can reproduce this issue by a simple calendar strip with scrollable enabled and calling the updateWeekView method via calendar ref to see this issue.

**Comment by rdewolff** [comment]
Could reproduce the issue with latest version `2.0.9`.

**Comment by peacechen** [comment]
Please submit a PR with the fix

**Comment by peacechen** [comment]
Fix published in 2.1.1
