### ISSUE TITLE
Possibility to add style to the whole date container component

### ISSUE THREAD

**Issue by dezse97** [BugiDev/react-native-calendar-strip#259]
Currently, we can add custom styles one by one for the name and the number. But what if we want to put the whole date container (name and number) in a circle or something like this.

**Comment by peacechen** [comment]
Try `dateContainerStyle` in customDatesStyles
https://github.com/BugiDev/react-native-calendar-strip#customdatesstyles

**Comment by dezse97** [comment]
Yes, it is an alternative way, but what if I would like to add a container style to the selected date?

**Comment by peacechen** [comment]
A new prop would need to be added e.g `selectedDateContainerStyle`. Please submit a PR with that added prop.
