### ISSUE TITLE
Title month and year

### ISSUE THREAD

**Issue by tiagobsbraga** [BugiDev/react-native-calendar-strip#26]
Is it possible to hide the title month and year?

**Comment by nolan-m** [comment]
Also looking for this feature.

**Comment by peacechen** [comment]
Calendar Strip is a straight-forward RN component written by @BugiDev that is relatively easy to understand.  Hiding the title shouldn't take too much effort.  I'll take a stab at it when I get some time. Pull requests are welcome.

**Comment by tiagobsbraga** [comment]
My simple solution:

`
<CalendarStrip
...
calendarHeaderStyle={{position: 'absolute', top: -100}}
...
/>
`

**Comment by peacechen** [comment]
Commit 047daf46301177b35bf5518be6629fca920831db adds prop `showMonth` to control whether to show the month label.

Also introduced other props to control whether to show the dates, day name/number, and selector icons.  See the Readme for details.
