### ISSUE TITLE
crash when passing datesWhitelist

### ISSUE THREAD

**Issue by HenriqueeLoopes** [BugiDev/react-native-calendar-strip#262]
Hi,

When I try to use the datasWhitelist parameter, the application stops working when assembling the component with the error:
'undefined is not an object (evaluating' dateList [_this.state.numVisibleDays - 1] .date) '.

If I don't use datasWhitelist and pass the key parameter, it is working normally.

**Comment by peacechen** [comment]
@HenriqueeLoopes Were you able to resolve the error? In the future please include a sample project or code snippet with relevant data.

**Comment by Vasault** [comment]
having exactly the same issue here, using the example from the documentation

**Comment by peacechen** [comment]
It may be a while until I can debug this. If you have time, it would help if you would debug it in the sample project. Set breakpoints in the CalendarStrip code where it throws an exception.
https://github.com/BugiDev/react-native-calendar-strip#development-with-sample-application
