### ISSUE TITLE
How to return selected date

### ISSUE THREAD

**Issue by techmodule** [BugiDev/react-native-calendar-strip#263]
Dear
First, thanks for this code, it is really beautifull and helpfull
I am newbee, so i want to know how to return selected date?
I try that, but it is not work
<Text>{getSelectedDate()}</Text>
Thanks

**Comment by peacechen** [comment]
The preferred way is to pass a callback to the `onDateSelected` prop.
https://github.com/BugiDev/react-native-calendar-strip#initial-data-and-ondateselected-handler

Refer to the sample project in this repo to get started quickly.
