### ISSUE TITLE
Ability to manipulate the text of the day so that only the first letter is capitalized

### ISSUE THREAD

**Issue by ysmike** [BugiDev/react-native-calendar-strip#265]
Changing the text format of the day from all uppercase to all lowercase (e.g. `TUE --> tue`) can be done by setting the prop: `dateNameStyle={{ textTransform: 'lowercase' }}`

However, if I'd like only the first letter capitalized, I'm not sure if there is a workaround for this since I cannot use pseudo elements (e.g. `::first-letter`). Does anyone how this might be done?

**Comment by peacechen** [comment]
The localization props allow you to customize any of the date strings.
https://github.com/BugiDev/react-native-calendar-strip#localization

**Comment by ysmike** [comment]
I set the `weekdaysShort` prop in the `locale` object to all lowercase but the calendar strip component is still rendering them in all caps. Is there anywhere else I can look to solve this issue? 

I also noticed that `moment.weeksdaysShort()` does not return days in all uppercase:`[
  'Sun', 'Mon',
  'Tue', 'Wed',
  'Thu', 'Fri',
  'Sat'
]`

**Comment by peacechen** [comment]
You're right, the day component changes it to uppercase 😮 
https://github.com/BugiDev/react-native-calendar-strip/blob/c8eb2caf90f38cc7394e8075b6800d4a70b35e46/src/CalendarDay.js#L481

Apologies for not catching that. We'll need to add a prop to control whether it does an uppercase on the day names. Would you mind submitting a PR with a new prop `upperCaseDays` (default to true)?

**Comment by peacechen** [comment]
PR merged and published in 2.1.9
