### ISSUE TITLE
Starting date changed when scrolling

### ISSUE THREAD

**Issue by rjuevesano** [BugiDev/react-native-calendar-strip#266]
Hello. I really need your help. I’m trying to add scrolling but the starting date has changed. If using arrows, it works fine.

Here’s my code:

```

<CalendarStrip
            ref={calendarStripRef}
            scrollable
            scrollerPaging
            showMonth={false}
            styleWeekend={false}
            useIsoWeekday={false}
            startingDate={dates[0]}
            style={{ height: 100 }}
            selectedDate={new Date()}
            scrollToOnSetSelectedDate={false}
            dayComponent={dayComponent}
            iconContainer={{
              alignItems: 'center',
              justifyContent: 'center',
              width: 20,
            }}
            iconLeft='angle-left'
            iconRight='angle-right'
            onWeekChanged={onWeekChanged}
          />
```

https://user-images.githubusercontent.com/4033035/106474459-e8bb3680-64df-11eb-8022-b91ab686526e.MP4

**Comment by rjuevesano** [comment]
Closing this issue. Got it working!

**Comment by Jeyoung-Park** [comment]
I'm facing the similar issue. 

I solved it by giving values to selectors like below.
`leftSelector={<View />}
 rightSelector={<View />}`
but I think it is not a perfect solutioin.

Can you tell me how you solved it?

**Comment by rjuevesano** [comment]
@Jeyoung-Park I'm using this configuration
```
<CalendarStrip
    scrollable={true}
    scrollerPaging={true}
    showMonth={true}
    styleWeekend={false}
    useIsoWeekday={true}
    startingDate={dates[0]}
    ...
/>
```

and created a patch to fixed it on my end
![image](https://user-images.githubusercontent.com/4033035/119624062-5c8ca080-be3b-11eb-9840-38613cdf0425.png)

**Comment by peacechen** [comment]
@rjuevesano 
Would you mind submitting a PR?

Your modification should be able to be simplified as such:
```
      if (useIsoWeekday) {
        // isoWeekday starts from Monday
        date = this.setLocale(_startingDate.clone().isoWeekday(i + 1));
      } else {
        date = this.setLocale(_startingDate.clone().add(i, "days"));
      }
```

Please validate that also works. Would prefer the simpler code in the PR.

**Comment by Jeyoung-Park** [comment]
@rjuevesano @peacechen 
in my case, both solution works.
Thanks for you help!

**Comment by peacechen** [comment]
2.2.2 has been published with @rjuevesano 's fix
