### ISSUE TITLE
scrollerPaging. The strip spins on 6 days for the first time, then – on 7 days

### ISSUE THREAD

**Issue by artcherenkov** [BugiDev/react-native-calendar-strip#269]
If the week starts on Monday, I want the bar to scroll until the next or previous Monday, but for some reason, when the first scroll, the bar spins for 6 days, and then properly - for 7 days.

My config:
```
<CalendarStrip
  scrollable
  scrollerPaging
  style={{ height: 200, paddingTop: 20, paddingBottom: 10 }}
  calendarColor={'#3343ce'}
  iconContainer={{ flex: 0.1 }}
/>
```

![ezgif com-gif-maker](https://user-images.githubusercontent.com/59122923/107139130-584f7c80-694b-11eb-981e-d11d117fc160.gif)

Someone know, how to fix it?

**Comment by Andrerm124** [comment]
I'm also facing this issue. Not sure on the cause but it makes the app look a little confusing at times.

**Comment by peacechen** [comment]
This may be a bug in the scrolling algorithm. Please use the demo project in this repo to debug and submit a PR.

https://github.com/BugiDev/react-native-calendar-strip#development-with-sample-application

**Comment by peacechen** [comment]
This has been published in 2.2.0

Thanks @psolom for the PR

**Comment by ozanmanav** [comment]
@peacechen Same issue happening on master branch. I'm setting starting of date as Monday. But it is again changing to Sunday when we scroll to next week.

**Comment by psolom** [comment]
@ozanmanav Make sure you set `minDate` and `maxDate` params, and the difference between values is a multiple of 7 - number of days in a week (14, 21, 28, etc). Works for me in versions of 2.2.0+

**Comment by ozanmanav** [comment]
@psolom Thanks for answer. Can you share a piece of code for this situation? In my case, it starts with Monday when it doesn't scroll at all, but when it scrolls it always becomes Sunday on the first day.
The props I am currently using for this are as follows.
```
  const startingDate = 2021-04-19

    scrollable = {true}
    scrollerPaging = {true}
    useIsoWeekday = {false}
    startingDate = {startingDate}
```

The first view is as follows:
![image](https://user-images.githubusercontent.com/19241756/115973392-5023d800-a55d-11eb-9f8c-2da1d8e42112.png)


But if I scroll it works like this:
![image](https://user-images.githubusercontent.com/19241756/115973398-544ff580-a55d-11eb-87cc-00508711f348.png)

**Comment by ozanmanav** [comment]
I think I found the problem. This problem happens when I close the left selector and right selector. When you open them, the problem disappears. I guess there is actually a little slip.

**Comment by rjuevesano** [comment]
@ozanmanav try this solution on this issue https://github.com/BugiDev/react-native-calendar-strip/issues/266
