### ISSUE TITLE
Change weeks based on date set programmatically?

### ISSUE THREAD

**Issue by nolan-m** [BugiDev/react-native-calendar-strip#27]
I have a header button labeled "Today" that when a user clicks should navigate them back to the current week.  Currently,  I can select the date fine (using Redux), but the weeks do not transition back.  Is this possible with the current architecture?

**Comment by peacechen** [comment]
That's a bug that should be fixable.  I'll take a look into it.

**Comment by peacechen** [comment]
@nolan-m  Do you use the `selectedDate` prop to bind to the Redux state?

**Comment by novose** [comment]
Hello,
I have the same problem on my app. But i don't use redux, I use a simple var with state in constructor => "selectedDate={this.state.selectedDate}". So I set the date of today with the button "today" in my header and it changes the selectedDate so the today's date, but it doesn't change the week. Maybe something is missing for me ?

I also found this method "updateWeekView" but I don't really know how to use it and if it helps.

**Comment by peacechen** [comment]
Try also setting the `startingdate` prop to the same value as `selectedDate`.  If you are using the default isoWeekView behavior, the week's start day will remain consistent.  If you've opted to disable isoWeekView, you'll need to call updateWeekView() and pass in the selected date as the first param.

**Comment by novose** [comment]
I actually have this : 
                            `<CalendarStrip
		            calendarAnimation={{type: 'sequence', duration: 30}}
	                    daySelectionAnimation={{type: 'border', duration: 200, borderWidth: 1, borderHighlightColor: 'white'}}
	                    style={{paddingTop: 20, paddingBottom: 10}}
	                    calendarHeaderStyle={{color: 'white'}}
	                    calendarColor={'#7743CE'}
	                    dateNumberStyle={{color: 'white'}}
	                    dateNameStyle={{color: 'white'}}
	                    highlightDateNumberStyle={{color: 'white'}}
	                    highlightDateNameStyle={{color: 'white'}}
	                    disabledDateNameStyle={{color: 'white'}}
	                    disabledDateNumberStyle={{color: 'white'}}
	                    datesWhitelist={this.state.datesWhitelist}
	                    datesBlacklist={this.state.datesBlacklist}
	                    iconContainer={{flex: 0.1}}
	                    onDateSelected={(value) => this.setState({selectedDate: moment(value).format("YYYY-MM-DD")})}
	                    selectedDate={this.state.selectedDate}
	                    useIsoWeekday={true}
	                    startingDate={this.state.selectedDate}
                            />`

I think calling updateWeekView() would be nice to test but I can't access this, and I don't understand how I have to do this "through the instantiated component's ref" as it's mentioned in the README.

Thanks for your quick answer.

**Comment by peacechen** [comment]
Follow the link in the Readme to React's ref documentation.  As an example:

```
<CalendarStrip
   ref={'myCalendarStrip'}
/>
```

In your component, access the CalendarStrip with `this.refs.myCalendarStrip`

**Comment by novose** [comment]
Ok, I tried this with the `"ref"` and the function `updateWeekView()` doesn't work, i have an 'undefined'. I tried another function like `getNextWeek()` and this one works, it selects the next week as it have to. But I was on release `0.1.3` so I tried to switch on the `0.1.4` but this time, unfortunatly, the entire calendar doesn't work, even if I try with your example in 'example' folder.
I have only the name of the month and the year with the `v0.1.4` :

![screenshot_1492161022](https://cloud.githubusercontent.com/assets/11664087/25039261/04e512b0-2103-11e7-8520-6d9248b77441.png)

**Comment by peacechen** [comment]
what parameter(s) did you pass to `updateWeekView` ?

**Comment by novose** [comment]
I added the height and now I can see the dates. And the function `updateWeekView` is working well, I am passing `moment()` to this function, it just didn't work with the `v0.1.3` I think but now it's great with the `v0.1.4`, it changes the date to today and the week to today's week.

Thank you for help!

**Comment by NothingSerious** [comment]
the function updateWeekView() doesn't work, i have an 'undefined'. How did you solve it? @ @novose

**Comment by novose** [comment]
Hi,

I'm not using it anymore, but i'm using `refs.myCalendarStrip.getPreviousWeek()`. Weirdly it does the trick. I needed to back to "today" and it's working. But if you want just to update the component view because of props changes I don't know if it will work, but you still can try. To be honnest I worked a long ago on that part of my project so... I guess it's still working
