### ISSUE TITLE
Add prettier to project

### ISSUE THREAD

**Issue by pedrobslisboa** [BugiDev/react-native-calendar-strip#274]
## Problem

The project doesn't have any prettier, so the code style doesn't follow any rule letting anyone commit formatted code

## Solution

Add prettier to project

## PS:

Here needed to be evaluated: training comma, `;` at the end, parentheses on one arg arrow function ...

**Comment by peacechen** [comment]
I used Prettier in the past, but it mangles JSX that has multiple props. This project heavily uses JSX and prettier will cause problems.
I recommend eslint which is more configurable and less opinionated.

**Comment by pedrobslisboa** [comment]
Eslint and prettier have different purposes https://prettier.io/docs/en/comparison.html

>In other words, use Prettier for formatting and linters for catching bugs!

I have never faced any problems with prettier, I guess a test for it should be nice.

**Comment by peacechen** [comment]
That may be some truth to that, but there is overlap. ESlint has built-in formatting capabilities too. That statement from prettier is more marketing gimmick than absolute truth 🤣 

https://www.digitalocean.com/community/tutorials/linting-and-formatting-with-eslint-in-vs-code
https://medium.com/@netczuk/even-faster-code-formatting-using-eslint-22b80d061461

**Comment by pedrobslisboa** [comment]
True

**Comment by peacechen** [comment]
If you have any recommendations for eslint configuration rules, please feel free to submit a PR. It is valuable to have a basic set of formatting behavior.
