### ISSUE TITLE
A question about dayComponent

### ISSUE THREAD

**Issue by Taher62** [BugiDev/react-native-calendar-strip#282]
Hello guys
I have a question about dayComponent customization
Is there any optimization for it? Actually I implement the dayComponet for custom Day view, but it is a bit slow when I select a day.
How I can optimize my day component?
Thank you

**Comment by peacechen** [comment]
Follow React best practices to minimize the number of re-renders:
https://reactjs.org/docs/optimizing-performance.html#avoid-reconciliation

A custom day component is beyond the scope of this forum and would be better suited for StackOverflow.
