### ISSUE TITLE
Error when selecting Date

### ISSUE THREAD

**Issue by HeinZawHtet** [BugiDev/react-native-calendar-strip#30]
When I select on date, error occurs like so...

![2017-04-12_13_06_57](https://cloud.githubusercontent.com/assets/1264755/24944428/30fbac0c-1f81-11e7-9e49-d16765901f74.jpg)

But onDateSelected() working when I click second time. No error is thrown.

Package Version - ^0.1.4
React Native version i used - 0.43.1

**Comment by peacechen** [comment]
I don't see `registrationName` anywhere in the CalendarStrip code.  Please post your code that uses CalendarStrip.

**Comment by capslock35** [comment]
has anyone solved this problem ?

**Comment by novose** [comment]
Hi,

I have the same issue since I installed `react-native: 0.43.4`

It was working perfectly on `react native: 0.42.*` but now when I click to change the date, I have this error.
Here's my code : 

> <CalendarStrip
		                calendarAnimation={{type: 'sequence', duration: 30}}
	                    daySelectionAnimation={{type: 'border', duration: 200, borderWidth: 1, borderHighlightColor: 'white'}}
	                    style={{height: 150, paddingTop: 20, paddingBottom: 10}}
	                    calendarHeaderStyle={{color: 'white'}}
	                    calendarColor={'#7743CE'}
	                    dateNumberStyle={{color: 'white'}}
	                    dateNameStyle={{color: 'white'}}
	                    highlightDateNumberStyle={{color: 'white'}}
	                    highlightDateNameStyle={{color: 'white'}}
	                    disabledDateNameStyle={{color: 'white'}}
	                    disabledDateNumberStyle={{color: 'white'}}
	                    iconContainer={{flex: 0.1}}
	                    onDateSelected={(value) => this.setState({selectedDate: moment(value).format("YYYY-MM-DD")})}
	                    selectedDate={this.state.selectedDate}
	                    ref='myCalendarStrip'
                    />

and I have `selectedDate` in my constructor, i change the date with that.

**Comment by capslock35** [comment]
Thanks A lot

**Comment by novose** [comment]
Sorry but I mean that I have the same error. The only way is to downgrade React native version, but I can't do that for my app, I need the last version of react native.
I guess it's coming from react native 0.43.* but I wonder how it would be solved.

**Comment by DemisBand** [comment]
+1 Same issue

**Comment by peacechen** [comment]
Sounds like it could be a breaking change with RN 0.43.  I'm not able to test it on that version yet.  Would appreciate help debugging this.

**Comment by samcolby** [comment]
This is only on Android right?  

As a quick fix you can change the following line in CalendarDay.js to convert ```this.props.date.date()``` to a string.  

```js
{ this.props.showDayNumber &&
    <Text style={dateNumberStyle}>{"" + this.props.date.date()}</Text>
}
```

**Comment by peacechen** [comment]
Thanks @samcolby for the work-around.  I'm hesitant to put in a band-aid for a transitory RN bug.  Once that patch is in, it's likely going to hang around forever and someone looking at it later will scratch their heads why it's there.  Cruft becomes a maintenance headache.  This issue isn't specific to react-native-calendar-strip; any component using a number in a touchable will trigger this RN bug.  Best bet would be to downgrade to RN 0.42 or use the 0.44 RC.
