### ISSUE TITLE
Type 'Date' is not assignable to type 'Moment'

### ISSUE THREAD

**Issue by sniib** [BugiDev/react-native-calendar-strip#300]
selectedDate, minDate, maxDate , startingDate props give the above ts error when passing date instead of moment date. According to docs those props should accept dates as well.

**Comment by chungweileong94** [comment]
@sniib Yes, it accepts both Moment & Date.
As for now, my temporary workaround is to use the [`patch-package`](https://www.npmjs.com/package/patch-package) to patch the type.

**Comment by peacechen** [comment]
@chungweileong94 Did you patch the TS definition? Please submit a PR with the fixes.

**Comment by chungweileong94** [comment]
@peacechen Just create a PR for that.
https://github.com/BugiDev/react-native-calendar-strip/pull/301

**Comment by peacechen** [comment]
Fix published in 2.2.3. Thanks for the PR @chungweileong94
