### ISSUE TITLE
Component exception: cannot read property scrollToIndex of undefined

### ISSUE THREAD

**Issue by nagesh-bv** [BugiDev/react-native-calendar-strip#306]
Hi there, Im facing this issue with the following version:
"react-native-calendar-strip": "^2.2.3"

![MicrosoftTeams-image](https://user-images.githubusercontent.com/69771443/123652014-904b5380-d849-11eb-9b25-ce13b2b7cbe2.png)

Thank you.

**Comment by nagesh-bv** [comment]
As I debug it and fount that **this.rlv** is coming **undefined**

**Comment by majugurci** [comment]
Can confirm, same thing happening in my app.
My home screen contains react-native-calendar-strip and when I change some file which reloads the whole app this is happening. If i make some smaller change which reloads only home screen then it is working fine.
Also this is happening in versions 2.2.3 and 2.2.2.
In version 2.2.1 everything is OK.

**Comment by rdoylespk** [comment]
@majugurci 

got the same problem today with version 2.2.4

Downgrading to 2.2.1 fixed the issue 

Thanks

**Comment by harking** [comment]
Yup, in 2.2.2, a change was made to add a scrollToDate on componentDidUpdate. If the component props change before the itemHeight is calculated, this.rlv will not be defined yet.

Rolling back to 2.2.1 will work-around until a fix is made.

Possible fixe: Add null check for this.rlv in this.scrollToDate

**Comment by peacechen** [comment]
Please create a PR that checks for `this.rlv`. Thanks for debugging this issue..

**Comment by peacechen** [comment]
Fix published in 2.2.6

Thanks @adamgajzlerowicz and everyone who contributed to this fix
