### ISSUE TITLE
code style fix: getSelectedDate() date argument is useless

### ISSUE THREAD

**Issue by julienbornstein** [BugiDev/react-native-calendar-strip#313]
https://github.com/BugiDev/react-native-calendar-strip/blob/8a32fc470cbdfa12d6298dcda14d9e5a91b20542/src/CalendarStrip.js#L315

should be replaced by 

```javascript
getSelectedDate = () => {
```

**Comment by peacechen** [comment]
Thanks for reporting this @julienbornstein

**Comment by peacechen** [comment]
Fix committed in 31ebd4c8250ffbd45203c0f3a2a0d283af2839f9
