### ISSUE TITLE
Change custom font

### ISSUE THREAD

**Issue by whyamsx** [BugiDev/react-native-calendar-strip#319]
Hello, I want to replace the font in the calendar with my pre-installed one, but for some reason this does not work, the font simply remains the same

this is how i do it:
`dateNumberStyle={{ color: 'white', fontFamily: 'Poppins-Medium', fontSize: 14 }}`

**Comment by sophea-we** [comment]
Hello @whyamsx, try this: `dateNumberStyle={{ color: 'white', fontFamily: 'Poppins-Medium', fontWeight: '500', fontSize: 14 }}`
