### ISSUE TITLE
Per-date custom styling

### ISSUE THREAD

**Issue by peacechen** [BugiDev/react-native-calendar-strip#32]
Add prop to support styling dates individually, independent of the global styling props.

**Comment by peacechen** [comment]
![image](https://cloud.githubusercontent.com/assets/6295083/25105759/a3335fc8-238b-11e7-9a92-3174498a0d89.png)

**Comment by lomo009** [comment]
not working. Trying to style today's date. Suggest a Today's date prop.

**Comment by peacechen** [comment]
It would be better to open a new issue with the code snippet you're using for the CalendarStrip.  Date styling should be similar to the example.
```
let startDate = moment();
customDatesStyles=[ {
      startDate, // Single date since no endDate provided
      dateNameStyle: {styles.someDateNameStyle},
      dateNumberStyle: {styles.someDateNumberStyle},
      // Random color...
      dateContainerStyle: {{backgroundColor: '#'+('#00000'+(Math.random()*(1<<24)|0).toString(16)).slice(-6)}},
}];

render() {
  return (
    <CalendarStrip
      customDatesStyles={customDatesStyles}
      ...
    />
  );
}
```

`styles.someDateNameStyle` and `styles.someDateNumberStyle` need to be defined of course.
