### ISSUE TITLE
Performance optimizations

### ISSUE THREAD

**Issue by peacechen** [BugiDev/react-native-calendar-strip#33]
[Slowlog](https://github.com/jondot/react-native-slowlog) has revealed bottlenecks in this component.  It's not too noticeable for a single instance of CalendarStrip, but when there are many of them active, things slow down in a hurry.

- `getDatesForWeek()` is slow ~20ms.
- `getDatesForWeek()` is called 4 times per render loop, once directly by render(), and another 3 times by formatCalendarHeader() which is called by render(). Instead of calling it every render loop, it need only be called when startingDate changes.
- `isDateAllowed()` and `getCustomDateStyle()` are called for each date in render() which is unnecessary.  That information need only be recalculated when their associated props change.
- `Animated.View` incurs a penalty when no animation prop is specified.  Conditionally substitute it for a regular `View`.
- `forEach()` incurs a function call penalty. Replace those with simple for loops.
- `map()` incurs a function call penalty. Replace it with a simple for loop.

**Comment by peacechen** [comment]
This commit has significantly changed how render() gets its data.  Instead of making expensive calls for every render loop, it references state variables.  Those state variables change only when their related props change.  I've tested this as thoroughly as I can, but would appreciate feedback from the community for any bugs that may have been overlooked.

**Comment by samcolby** [comment]
Hey peachechen.  

There's a bit too much going on in here to really give some good feedback on this (and I'm probably not close enough to the code anyway).  It does all seem to be working fine for how I'm using though.

However, I do think the current components are a bit too big to really get a handle on how often everything is being rerendered and what is actually happening on each render.  If you split things out into a few more separate Components something like CalendarHeader, WeekSelector, CalendarDayHighlight etc. Maybe even move to a smart/dumb strategy for the main CalendarStrip component.  It should hopefully then make everything a lot simpler to reason about and also easier to maintain.

Just my 2 cents...

**Comment by peacechen** [comment]
I don't disagree that the code is getting fat.  I tried to keep it as minimal as possible, but just the length of it makes it harder to digest.  That's a good idea to split some of the code into separate components.  The tradeoff would be additional nodes in the render tree which has the potential to slow things down.  Would be worth experimenting to see how much.
My app has dozens of CalendarStrip instances in a list and the (slow) performance is very obvious.  	Commit 18247ec has increased render performance by a factor of 2.  I hope to improve it further but the speedup is already noticeable in my app.

**Comment by samcolby** [comment]
Shall we keep the performance discussion here rather than in the PR?

Your right about using shouldComponentUpdate, but it is hard to figure out why things are happening if it is all in the same component.  

I've found that by creating lots of smaller and simpler components, it makes it much easier to then look at each one in isolation.  For instance, it is fairly trivial to see that each CalendarDay instance renders twice onload and also each time you switch a date, but if the CalendarDay logic was in the main CalendarStrip, you would probably have no idea.  

Nice performance improvements though !  I'm only using a couple of instances in my app, so not really noticing anything obviously slow.  Where are you noticing that there is bad performance?

**Comment by samcolby** [comment]
As a really nasty fudge.  Does the following make things any better, when changing dates?

```js
//Handling press on date/selecting date
  onDateSelected(selectedDate) {
    //this.setState({ selectedDate }, () =>
    this.state.selectedDate = selectedDate;
    this.updateWeekData(this.state.startingDate);
    //);

    this.props.onDateSelected && this.props.onDateSelected(selectedDate);
  }
```

**Comment by peacechen** [comment]
My app has dozens of CalendarStrip instances in a ScrollView.  Instead of each one having their own prev/next controls, I have one master control that advances the weeks for all of them.  The lag increases linearly with the number of instances.  Up to about 10 it's bearable.  Over 30 and it climbs to over a second.  I've considered paging the ScrollView but that's not a great user experience for our use case.  Interacting with each calendar's dates is fine.  It's advancing week to week that's a big bottleneck.

I tried your suggestion of mutating state directly with no appreciable speedup.  I'm concerned about doing that because the [React docs ](https://facebook.github.io/react/docs/react-component.html) say 
> Never mutate this.state directly, as calling setState() afterwards may replace the mutation you made. Treat this.state as if it were immutable.

**Comment by samcolby** [comment]
Hi, yes, not suggesting that that is the answer.  Just a quick fudge to cut down on the number of renders, to see if it help.  In my app that stops each CalendarDay instance from rendering twice, when you select a date.

Where are you seeing the performance issue then?  I would have expected the above to show a noticeable improvement.

**Comment by peacechen** [comment]
Instantiating ~50 CalendarStrips in our app takes on the order of 2-3 seconds.  About half of that time is CalendarStrip instances coming up.  There is room for improvement in both our component logic and CalendarStrip.  It's been challenging narrowing down the root cause of the performance bottlenecks.  Bypassing setState and mutating state directly doesn't improve performance at all that I can see from slowLog.

**Comment by samcolby** [comment]
Can you move the setState calls from the ComponentDidMount in CalendarStrip?  I'm fairly sure that that logic can just happen in the constructor.  

https://github.com/BugiDev/react-native-calendar-strip/blob/master/src/CalendarStrip.js#L124

```js
componentDidMount() {
    // Initialize week view
    let startingDate = this.updateWeekView(); // Force update
    this.updateWeekData(startingDate);
    // Animate showing of CalendarDay elements
    this.animate();
}
```


Currently, the CalendarStrip does the following

1. Calls the constructor
2. Calls the render method
3. Call componentDidMount (which calls setState twice)
4. Calls the render method

Getting rid of step 4 has got to help.

**Comment by samcolby** [comment]
This wont help, the initial loading speed, but you should also be able to refactor the setState calls so that they only get called once for every action. The easiest way to do this would be to include the setState call in the body of the action 'function' itself and then having updateWeekData/View just return the correct values for setState

At the moment you have

* componentDidMount (called twice)
* componentWillReceiveProps (possibly called 5 times(?))
* getPreviousWeek (3 times)
* getNextWeek (3 times)
* onDateSelected (3 times with the updater function)
* setSelectedDate (4 times)

**Comment by peacechen** [comment]
Your expert setState analysis was spot on.  I've made the improvements you suggested in CalendarStrip as well as our internal components' logic which has increased performance measurably.  I hope to reduce the list instantiation time to under 1 second and will push the changes.

**Comment by samcolby** [comment]
Awesome :)  I wasn't expecting that much improvement.  Maybe 25%, but well done. 

So, [PureComponents](https://60devs.com/pure-component-in-react.html) next ?  

BTW,  I'm not sure how you are using so many calendar-strip instances, but if you can use a ListView or FlatList to display them it should load pretty much instantaneously.  See the top of this page as to why it will improve performance https://facebook.github.io/react-native/docs/scrollview.html

**Comment by peacechen** [comment]
PureComponent sounds great. I always felt that there was too much boilerplate needed for componentWillReceiveProps and that they'd address it eventually.

Thanks for the tip on FlatList! That sounds like it could have a big performance impact.

**Comment by samcolby** [comment]
No worries, be careful with PureComponents.  They are hard to get right, and doubly so because of the amount of moment instances used in here.  

That JSON.stringify trick I used in the WeekSelector and CalendarHeader should get you most of the way there without too much risk if you start looking at that.

**Comment by peacechen** [comment]
It looks like the Moment JS calls are relatively expensive.  `updateWeekData` makes these calls which reference Moment JS:

isDateAllowed -> Moment `isBetween` or `isSame`
isDateSelected -> `isSame`
getCustomDateStyle -> `isBetween` or `isSame`

Each of those calls adds 10-12 ms as reported by slowLog (which incurs some debug penalty; a release build would be less).

**Comment by samcolby** [comment]
If that's the slowest thing, then I'm not sure there's too much to worry about. 

But I'm surprised isSame is so slow.
https://github.com/moment/moment/blob/497f918515ae6ab900f008f19523b1e4ae5e2450/src/lib/moment/compare.js#L38

moment wraps Date internally, so its bound to be slower  

Or there's always [xDate](http://arshaw.com/xdate/#Diffing)

**Comment by peacechen** [comment]
I think we've gotten the bulk of performance improvements.  Spending more time on it would be trying to squeeze blood from a rock.  I'll close it for now, but if anyone has any more suggestions feel free to re-open.
