### ISSUE TITLE
startingDate prop does not center the date.

### ISSUE THREAD

**Issue by corybcromer** [BugiDev/react-native-calendar-strip#343]
According to the documentation, the startingDate prop should center the assigned date; however, my implementation is not working. I thought the view container which it is called in might be inadvertently passing on styles. I test this out by passing in different values to alignItems, alignContents, and justifyContent, but this does not seem to be the culprit.

Here is my implementation:

```
import React from 'react'
import CalendarStrip from 'react-native-calendar-strip'
import { StyleSheet } from 'react-native'

const HorizontalCalendar = () => {
  return (
    <CalendarStrip
        scrollable
        style={styles.calendarStyle}
        calendarColor={'transparent'}
        iconContainer={{flex: 0.002,}}
        startingDate={new Date()}
        selectedDate={new Date()}
        rightSelector={[]}
        leftSelector={[]}
        dayContainerStyle={{}}
        dateNumberStyle={styles.calendarDateNumber}
        highlightDateNumberStyle={styles.calendarHighlightDateNumber}
        dateNameStyle={styles.calendarDateName}
        highlightDateNameStyle={styles.calendarHighlightDateName}
        highlightDateContainerStyle={styles.calendarHighlightDateContainer}
        calendarHeaderStyle={styles.calendarHeader}
        calendarHeaderPosition='below'
        calendarHeaderFormat='MMMM'
    />
  )
}

export default HorizontalCalendar

const styles = StyleSheet.create({
calendarStyle: {
        height: '20%',  
        paddingBottom: 10,
    },
    calendarDateNumber: {
        color: '#4B4046',
        fontSize: 18,
        fontWeight: '400',
    },
    calendarHighlightDateNumber: {
        color: '#FDFCFD',
        fontSize: 18,
        fontWeight: '700',
    },
    calendarDateName: {
        color: '#8E7C87',
        fontSize: 12,
        fontWeight: '400',
    },
    calendarHighlightDateName: {
        color: '#FDFCFD',
        fontSize: 12,
        fontWeight: '400',
    },
    calendarHighlightDateContainer: {
        backgroundColor: '#C11277',
        borderRadius: 8,
    },
    calendarHeader: {
        color: '#8E7C87',
        fontSize: 16,
        fontWeight: '700',
    },
})

```

This is the rendered view:
![Simulator Screen Shot - React Simulator - 2022-04-06 at 18 44 31](https://user-images.githubusercontent.com/50381075/162084764-773cd121-8028-41bd-b966-b666024509fe.png)

**Comment by msozaev** [comment]
@corybcromer Just add useIsoWeekday={false} it will center like you need need.

"start week on ISO day of week (default true). If false, starts week on startingDate parameter."

**Comment by corybcromer** [comment]
Thanks for the suggestion. I tried adding that prop, and I am having the same issue. Any other thoughts?

**Comment by rafaelvicio** [comment]
same here

**Comment by corybcromer** [comment]
@peacechen could you possibly take a look at this please? I went through the projects source code, but I cant find the issue.

**Comment by corybcromer** [comment]
@peacechen Could you possibly take a look at this? I went through the source code, but I cant find the problem.

**Comment by peacechen** [comment]
Centering the selected date isn't a feature. The documentation that mentions "centering" is for the week, not a specific day. Please submit a PR if you'd like to add a prop for that.

One way to implement this in your app is to set `useIsoWeekday={false}`, then set the `startingDate` prop offset to the date needed to center `selectedDate`. In your example with selectedDate set to Wed, the startingDate should be Sun.

**Comment by corybcromer** [comment]
@peacechen Thank you so much! I did not understand the phrasing of the documentation. I thought `startingDate` centered the week on that specific day. So if I set it to Wednesday, I thought Wednesday would be in the center of the strip. I didnt know the `startingDate` you selected would be placed at the beginning of the calendar strip. It might help to clarify this under the props description of `startingDate` so that dummies like me wont get confused, but it could just have been me. Thanks again for responding so quickly. I love the repo.

**Comment by peacechen** [comment]
Yes the documentation could use improvement. PRs are welcome for anything including documentation 😄 

Hope you were able to get the centering working.

**Comment by anniewey** [comment]
@peacechen is there a way to center the selected date in the strip, same behaviour as when user press on certain dates - will auto centered? my date range is within 15 days before and after today's date.

```
  const today = new Date();

  const startDate = new Date(today);
  startDate.setDate(today.getDate() - 15);

  const endDate = new Date(today);
  endDate.setDate(today.getDate() + 15);

 <CalendarStrip
            scrollable
            styleWeekend={false}
            dayComponentHeight={70}
            selectedDate={today)}
            minDate={startDate}
            maxDate={endDate}
            style={{
              marginBottom: CustomSize.Padding20,
            }}
            leftSelector={[]}
            rightSelector={[]}
            showMonth={false}
            locale={{
              name: 'en',
              config: {
                weekdaysShort: 'S_M_T_W_T_F_S'.split('_'),
              },
            }}
          />
```

Update:
Able to get it work by using `ref` and `scrollToOnSetSelectedDate` to false

```
useEffect(() => {
if (calendarRef?.current) {
      setTimeout(() => calendarRef.current?.setSelectedDate(new Date()), 300);
    }
},[]);

<CalendarStrip
            ref={calendarRef}
            scrollable
            styleWeekend={false}
            scrollToOnSetSelectedDate={false}
            useIsoWeekday={false}
            dayComponentHeight={70}
            // selectedDate={new Date()}
            minDate={startDate}
            maxDate={endDate}
            style={{
              marginBottom: CustomSize.Padding20,
            }}
            leftSelector={[]}
            rightSelector={[]}
            showMonth={false}
            locale={{
              name: 'en',
              config: {
                weekdaysShort: 'S_M_T_W_T_F_S'.split('_'),
              },
            }}
          />
```
