### ISSUE TITLE
 TypeError: Cannot read property 'scrollToDate'

### ISSUE THREAD

**Issue by strelov1** [BugiDev/react-native-calendar-strip#367]
When I try to select another date with the ref I have this error

TypeError: Cannot read property 'scrollToDate'

<img width="351" alt="CleanShot 2023-05-04 at 10 48 21@2x" src="https://user-images.githubusercontent.com/10761735/236142240-00056f5f-0ab8-4ae3-88f5-35aae9cebd73.png">

Here is my configuration

```ts
const calendarRef = useRef(null);
const nextDay = () => {
       if (calendarRef.current) {
            const addOneDay = new Date(currentDate);
            addOneDay.setDate(currentDate.getDate() + 1);
            calendarRef.current.setSelectedDate(addOneDay.toISOString())
        }
}

return (
<CalendarStrip
   ref={calendarRef}
   calendarAnimation={{type: 'sequence', duration: 30}}
   style={styles.calendarStrip}
   onDateSelected={onDateChange}
/>
)
```

**Comment by tanyicheng** [comment]
You need to add scrollable={true} to your code. like this
<CalendarStrip
   ref={calendarRef}
   scrollable={true} 
   calendarAnimation={{type: 'sequence', duration: 30}}
   style={styles.calendarStrip}
   onDateSelected={onDateChange}
/>

**Comment by strelov1** [comment]
Thanks @tanyicheng. It's helped
