### ISSUE TITLE
Change language

### ISSUE THREAD

**Issue by basequatro** [BugiDev/react-native-calendar-strip#4]
How i can change the language and date format?

**Comment by basequatro** [comment]
Added to calendarstrip, maybe adding a props for this would be a good idea.
`import esLocale from 'moment/locale/es';`

**Comment by BugiDev** [comment]
@basequatro Thank you for the suggestion! I have added localization and publish it in a v0.1.0

**Comment by idrisdopico** [comment]
Is this enhancement added?

**Comment by nppull** [comment]
` import esLocale from 'moment/locale/es;`

thanks you, this line help me
