### ISSUE TITLE
onStartShouldSetResponder issue

### ISSUE THREAD

**Issue by RamonAcedoM** [BugiDev/react-native-calendar-strip#40]
I'm having this issue once i click on three or four dates in the calendar strip. 

If i randomly click the dates this is shown:

![screen shot 2017-05-07 at 12 39 37 pm](https://cloud.githubusercontent.com/assets/8166418/25784479/9d7c6b0a-3322-11e7-8aa0-fdf61cbb9415.png)

Notes: I'm on react native 0.43.4 Using the latest version of Calendar Strip

**Comment by peacechen** [comment]
CalendarStrip isn't handling [gestures](https://facebook.github.io/react-native/docs/gesture-responder-system.html) so `onStartShouldSetResponder` isn't directly caused by CalendarStrip.  Is your app handling gestures?  If not, I wonder if this is another RN 0.43 bug (see #30).

**Comment by peacechen** [comment]
Closing due to no response
