### ISSUE TITLE
SyntaxError left-arrow-black.png 

### ISSUE THREAD

**Issue by lossen** [BugiDev/react-native-calendar-strip#47]
SyntaxError /node_modules/react-native-calendar-strip/src/img/left-arrow-black.png: Unexpected character

Hello.
How fix this issue? 
my code: 
`<CalendarWeek
                      calendarAnimation={{type: 'sequence', duration: 30}}
                      daySelectionAnimation={{type: 'border', duration: 200, borderWidth: 1, borderHighlightColor: 'white'}}
                      style={{height: 100, paddingTop: 20, paddingBottom: 10}}
                      calendarHeaderStyle={{color: 'white'}}
                      calendarColor={'#7743CE'}
                      dateNumberStyle={{color: 'white'}}
                      dateNameStyle={{color: 'white'}}
                      highlightDateNumberStyle={{color: 'yellow'}}
                      highlightDateNameStyle={{color: 'yellow'}}
                      disabledDateNameStyle={{color: 'grey'}}
                      disabledDateNumberStyle={{color: 'grey'}}
                      iconContainer={{flex: 0.1}}/>`

**Comment by peacechen** [comment]
Possibly a RN bug.
https://github.com/facebook/react-native/issues/6691

A suggested workaround is to restart the package manager.

**Comment by lossen** [comment]
This workaround did not help :(

**Comment by peacechen** [comment]
Did that resolve the error?  Please close the issue if it did, or post a followup with more details.
