### ISSUE TITLE
highlightColor not working

### ISSUE THREAD

**Issue by lossen** [BugiDev/react-native-calendar-strip#49]
Hello
highlightColor not working
my code:

`<CalendarStrip
                      calendarAnimation={{type: 'sequence', duration: 30}}
                      selection={'background'}
                      selectionAnimation={{duration: 300, borderWidth: 1}}
                      style={{paddingTop: 20, paddingBottom: 10}}
                      calendarHeaderStyle={{color: 'rgb(102, 120, 144)', fontSize:15, lineHeight:15, fontWeight:'400'}}
                      calendarColor={'transparent'}
                      highlightColor={'rgba(57, 63, 98, 0.05)'}
                      dateNumberStyle={{color: 'rgb(97, 114, 136)', fontSize:15, fontWeight:'400'}}
                      dateNameStyle={{color: 'rgb(171, 183, 203)', fontSize:11}}
                      highlightDateNumberStyle={{color: 'rgb(79, 155, 235)',fontWeight:'400'}}
                      highlightDateNameStyle={{color: 'rgb(79, 155, 235)'}}
                      iconContainer={{flex: 0.1}}
                      styleWeekend={false}/>`

![simulator screen shot 9 2017 12 22 37](https://user-images.githubusercontent.com/14949813/29107737-72b5b8b6-7cfd-11e7-816e-679857ebbd97.png)

**Comment by peacechen** [comment]
Please refer to the Readme for `highlightColor`.  It's part of the `daySelectionAnimation` object prop.  The example project may also be helpful.
https://github.com/BugiDev/react-native-calendar-strip/blob/master/example/ReactNativeCalendarStripExample/index.ios.js
