### ISSUE TITLE
Should check if prosps passed locale

### ISSUE THREAD

**Issue by zhuzhuojiang** [BugiDev/react-native-calendar-strip#5]
Line 127: momentInstance.locale(this.props.locale.name); 
Needs to check if locale passed. It will report error if user not passed

**Comment by 1ne8ight7even** [comment]
Created PR: https://github.com/BugiDev/react-native-calendar-strip/pull/6

**Comment by BugiDev** [comment]
@1ne8ight7even Fixed it with PR: #6
