### ISSUE TITLE
How can i change the locale to turkey ?

### ISSUE THREAD

**Issue by hulusimizrak** [BugiDev/react-native-calendar-strip#52]

**Comment by peacechen** [comment]
Refer to the Readme for [locales](https://github.com/BugiDev/react-native-calendar-strip#localization).  CalendarStrip uses Moment JS internally so the same object is passed on to [Moment's i18n module](http://momentjs.com/docs/#/i18n/).

The config object allows you to provide any translations you like for the days, months, etc.

**Comment by hulusimizrak** [comment]
@peacechen thank you so much :)
