### ISSUE TITLE
Date number press on error (undefined is not an object(evaluating '_props[registrationName]')

### ISSUE THREAD

**Issue by hulusimizrak** [BugiDev/react-native-calendar-strip#53]
Error Screen shot:
https://i.hizliresim.com/nWBZ2g.png

**Comment by peacechen** [comment]
@hulusimizrak 
There's no `registrationName` in the CalendarStrip code.  You may want to double check to see if it's in your app code.

**Comment by hulusimizrak** [comment]
you right thanks, 
Can I cancel the press of the number of dates ?

**Comment by peacechen** [comment]
Refer to the [Readme under the props section](https://github.com/BugiDev/react-native-calendar-strip#props--api).   Prop `datesBlacklist` will disable dates, and you can change their default styling with `disabledDateNameStyle` and `disabledDateNumberStyle`.

**Comment by hulusimizrak** [comment]
@peacechen actually I want to do,

disabledDateNumberStyle={{color: 'grey',**onPress:'false'**}}
highlightDateNumberStyle={{ color: 'blue',**onPress:'false'** }}
