### ISSUE TITLE
Plugin is Not working

### ISSUE THREAD

**Issue by URvesh109** [BugiDev/react-native-calendar-strip#54]
plugin is not working. I am using react native v0.47

**Comment by peacechen** [comment]
What's the error?  Code snippet would help too.  I've tested up to RN 0.45.1 and it works ok.

**Comment by URvesh109** [comment]
Only <Calendar/> doesn't work.
but  this work as expected
  <CalendarStrip
              calendarAnimation={{type: 'sequence', duration: 30}}
              daySelectionAnimation={{type: 'border', duration: 300, borderWidth: 2, borderHighlightColor: 'white'}}
              style={{height:100, paddingTop: 20, paddingBottom: 10}}
              calendarHeaderStyle={{color: 'white'}}
              calendarColor={'#7743CE'}
              dateNumberStyle={{color: 'white'}}
              dateNameStyle={{color: 'white'}}
              iconLeft={require('./img/left-arrow.png')}
              iconRight={require('./img/right-arrow.png')}
              iconContainer={{flex: 0.1}}
          />

**Comment by peacechen** [comment]
Some props are required.  What is the error message when it fails?

Pull requests are welcome if you have a good idea of how to handle an empty props list.
