### ISSUE TITLE
How can we set Sunday as first day of week?

### ISSUE THREAD

**Issue by ervishu83** [BugiDev/react-native-calendar-strip#57]
I would like to set Sunday as first day for week for CalendarStrip.

I had tried with both:
`useIsoWeekday: true`
also
`useIsoWeekday: false`

but it didn't helped.

**Comment by peacechen** [comment]
Please refer to the [Readme on props](https://github.com/BugiDev/react-native-calendar-strip#initial-data-and-ondateselected-handler):

> useIsoWeekday: PropTypes.bool - start week on ISO day of week (default true). If false, starts week on **startingDate** parameter.

Pass in the **startingDate** prop to specify which day/date the week starts on.

**Comment by ervishu83** [comment]
Can I have example of this?

**Comment by peacechen** [comment]
```
<CalendarStrip
  useIsoWeekday={false}
  startingDate={moment("10-31-2017", "MM-DD-YYYY")}
/>
```
