### ISSUE TITLE
Can't render calendar in android

### ISSUE THREAD

**Issue by apurvthakkar99** [BugiDev/react-native-calendar-strip#59]
I have installed npm dependency and try to render calendar in view but can't see anything in the screen.

**Comment by peacechen** [comment]
Does the [example](https://github.com/BugiDev/react-native-calendar-strip/tree/master/example/ReactNativeCalendarStripExample) work for you?

Thread #31 may help as well.

**Comment by apurvthakkar99** [comment]
Yes the example works for me.Actually I tried to render <CalendarStrip> with color and all properties and it works.
Thanks.
