### ISSUE TITLE
Calendar animation when week changes is different than when component loads

### ISSUE THREAD

**Issue by fgonzalezm** [BugiDev/react-native-calendar-strip#63]
When the component initially loads, all the days cannot be seen and then each day appears one by one starting from the left. However, when a user changes the week, the animation is not the same. When the week is changed, the days just blink in and out one by one. It would be better if the animation was the same both times.
Also, the animation reversing depending on whether you go to the previous week or the next week would be really cool.

**Comment by peacechen** [comment]
That would be a nice enhancement. I'm not sure when I'll be able to work on this.  It would be a great help if you would submit a PR.

**Comment by peacechen** [comment]
This has been fixed in the current release.
