### ISSUE TITLE
Android Example has cutoff

### ISSUE THREAD

**Issue by tyricec** [BugiDev/react-native-calendar-strip#64]
Hi,

I started a new sandbox react-native app using this library and I see the following when using the example code:

![screenshot_20171205-123638](https://user-images.githubusercontent.com/3968741/33629492-18ca460a-d9b9-11e7-94d5-30e87bb14222.png)

# Code:

```
<View>
        <CalendarStrip
          calendarAnimation={{type: 'sequence', duration: 30}}
          daySelectionAnimation={{type: 'border', duration: 300, borderWidth: 2, borderHighlightColor: 'white'}}
          style={{height:100, paddingTop: 20, paddingBottom: 10}}
          calendarHeaderStyle={{color: 'white'}}
          calendarColor={'#7743CE'}
          dateNumberStyle={{color: 'white'}}
          dateNameStyle={{color: 'white'}}
          iconContainer={{ flex: 0.1 }}
        />
</View>
```

Seems to relate to #22

I tried using maxDayComponentSize, but that doesn't seem to change anything for me. Any ideas?

# Software Info:

react-native: "0.50.3"
react-native-calendar-strip: "^1.2.4"

# Device Info:

Model: Google Pixel

OS: Android 8.0.0

**Comment by peacechen** [comment]
What values have you tried for `maxDayComponentSize` ?  Use the inspector and report the size of the individual day components.  It could be that the sizing isn't hitting the max value you're providing.

Another option is `responsiveSizingOffset`.  Setting a negative value will scale down the responsive sizing accordingly.

**Comment by tyricec** [comment]
Just figured out it was a hot reloading problem smh. Added back maxDayComponentSize with value 48 fixed my issue.

![screenshot_20171205-143101](https://user-images.githubusercontent.com/3968741/33634504-3a4e5a9a-d9c9-11e7-9205-7e8e429fccbb.png)

Thanks for the fast response.

**Comment by thorbenprimke** [comment]
Isn't this related to overflow not being supported / items being clipped on Android (https://github.com/facebook/react-native/issues/6802). 

Changing `maxDayComponentSize={xx}` fixes it but it's just a workaround as far as I understand it.

**Comment by chilidoggca** [comment]
maxDayComponent={48} is still too small on small devices. I like the idea of separating the background from the dayComponent to bypass android's overflow clipping

**Comment by peacechen** [comment]
A PR would be much appreciated :)
