### ISSUE TITLE
Updated ReadMe File

### ISSUE THREAD

**Issue by Burnsy** [BugiDev/react-native-calendar-strip#66]
Hey All,

I have been implementing this repo into one of my projects and it works great, but I felt the documentation could do with a rewrite to make it a bit clear.  I have started on rewriting it on my own Fork.  Any Suggestions Would be great. 

Take a look [here](https://github.com/Burnsy/react-native-calendar-strip/tree/UpdatedReadMe)

**Comment by peacechen** [comment]
Thanks for polishing the Readme.  It looks very nice.  Small typo:  `Pick witch` should be `Pick which`

I'll spend a little more time reviewing it, but I'd be happy to merge your PR.

**Comment by peacechen** [comment]
The link to React ref documentation is broken.  It's the line
`Methods may be accessed through the instantiated component's ref.`

**Comment by Burnsy** [comment]
Great.
There is probably a few small typos around the file. Sometimes my Dyslexia makes me miss a few. 

That broken link must have been carried over from the old file, in some places I did just copy and paste the content over.

**Comment by peacechen** [comment]
Yes you're right, it's in the original Readme too.

The line `Or open up a issue.` should be `Or open up an issue.`
Small things :)

**Comment by Burnsy** [comment]
Fixed them issues for you 🎉

**Comment by peacechen** [comment]
Thanks Burnsy  👍
If you'd like collaborator access (commit & merge PRs), contact @BugiDev.  Your documentation updates are valuable.

There's one more `Pick witch` typo in the Readme.  I was about to merge and scanned through it again.

**Comment by BugiDev** [comment]
@Burnsy Thank you so much for you commits. :)
If you have some time, just say the word and I'll provide the access. :)

**Comment by Burnsy** [comment]
Fixed the spelling error! Also I would love access, as I am going to make some additions to the project for our app! 

- Such As notifications per icon (possibly) 
- Also maybe adding different styles. I hacked it together and it looked great, so I want to add the relevant props types if needed.
- look into scroll to change week

![screen shot 2017-12-19 at 15 19 16](https://user-images.githubusercontent.com/15834048/34163924-046c25a8-e4d0-11e7-8ce3-8e6f2a91902b.png)

**Comment by peacechen** [comment]
That looks slick @Burnsy 

When you get collaborator access, I recommend that you work on branches since you like to make a lot of commits.  Nothing wrong with that, but it can be difficult to follow changes if two people are pushing interleaved commits.

**Comment by BugiDev** [comment]
@Burnsy I added you to collaborators list. Btw the new style looks really good. :)

**Comment by Burnsy** [comment]
Fixed Last Errors and merged into Master!
