### ISSUE TITLE
week start end

### ISSUE THREAD

**Issue by itcurves** [BugiDev/react-native-calendar-strip#7]
How I can get visible week start and end date, and is there any event when week change?

**Comment by BugiDev** [comment]
@itcurves What do you mean by visible week start and end date? Can you provide a use case.

Also there is no currently an event for when the week is changed, but will be added in future releases.

**Comment by BugiDev** [comment]
@itcurves We have just published a new version v0.1.3 that adds the feature of having an "event" for week change.
