### ISSUE TITLE
Add support for different number of days shown

### ISSUE THREAD

**Issue by rishiankush** [BugiDev/react-native-calendar-strip#75]
I want to implement like this:
![screen shot 2018-01-05 at 6 26 41 pm](https://user-images.githubusercontent.com/25289937/34610223-26c1b7ca-f246-11e7-8011-8750c7ef12b7.png)

Do this module include any property to make a view with 3 days?

**Comment by peacechen** [comment]
CalendarStrip currently doesn't support changing the number of days shown, but it would be relatively straight-forward to do so.  `numDaysInWeek` could be turned into a prop to allow control by the user.  There may be some minor adjustments elsewhere to get it all to work, but shouldn't be too much.

https://github.com/BugiDev/react-native-calendar-strip/blob/master/src/CalendarStrip.js#L97

**Comment by ismailkhan89** [comment]
Hello @rishiankush,
Do you have done this? if yes then kindly share your code ..

**Comment by peacechen** [comment]
@rishiankush @ismailkhan89 

This feature has been added with the `numDaysInWeek` prop.  If you want it centered on a particular date, use the `useIsoWeekday` and `startingDate` props.  Here's an example to center on today's date with 3 days in the week.

```
  // startingDate is always the left-most date when useIsoWeekday={false}
  <CalendarStrip
    numDaysInWeek={3}
    useIsoWeekday={false}
    startingDate={moment().subtract(1, "day")}
  />
```

This feature will be published in the next release.  To use it now, point to this repo directly in `package.json`.  Run `npm install` after changing it.
```
  "dependencies": {
    "react-native-calendar-strip": "https://github.com/BugiDev/react-native-calendar-strip",
    ...
  }
```
