### ISSUE TITLE
I want only 3 days like  previous  date  ,current date and next date

### ISSUE THREAD

**Issue by santoshzp** [BugiDev/react-native-calendar-strip#78]
I want only 3 days like  previous  date  ,current date and next date
if i press leftIcon then go back one day before and if i press  RightIcon then go to next date
also i want to show day visible

**Comment by peacechen** [comment]
Dup of #75

**Comment by peacechen** [comment]
@santoshzp 

https://github.com/BugiDev/react-native-calendar-strip/issues/75#issuecomment-643816508
