### ISSUE TITLE
Highlighting specific dates

### ISSUE THREAD

**Issue by peacechen** [BugiDev/react-native-calendar-strip#8]
Is there currently a way to highlight certain dates, irrespective of the focused/selected date?

The use case would be an itinerary.  For a given week, say there are events on Monday, Thursday & Friday.  I'd like to highlight those in different colors to indicate something is happening on those dates.

Also another loosely related question:  Is there a way to change the highlight shape from circle to square?

Thanks for releasing this handy component.

**Comment by BugiDev** [comment]
There is no currently a way to add highlight to certain dates, but I would love to add this and work on this with you @peacechen if you have some ideas. 
Also, there is no current way of changing circular shape, but I am planing a big refactor of the component, where I will add gestures and I can also add changing the shape.

**Comment by peacechen** [comment]
@BugiDev  Sounds great. Sent you an email

**Comment by peacechen** [comment]
I've implemented whitelist/blacklist props to enable/disable dates (or date ranges).  This is a step towards highlighting individual dates.  I'll submit the PR as soon as the previous ones are merged.
