### ISSUE TITLE
daySelectionAnimation is not applied while customDatesStyles defined

### ISSUE THREAD

**Issue by thanh-dong** [BugiDev/react-native-calendar-strip#82]
Hi, I want to apply a custom date style for a date (eg: today) and it's look like the day selection animation was overridden. I think the issue come from this block of code:

```
   if (customStyle) {
      dateNameStyle = [styles.dateName, customStyle.dateNameStyle];
      dateNumberStyle = [styles.dateNumber, customStyle.dateNumberStyle];
      dateViewStyle.push(customStyle.dateContainerStyle);
    } else if (this.props.enabled) {
      // Enabled state
      //The user can disable animation, so that is why I use selection type
      //If it is background, the user have to input colors for animation
      //If it is border, the user has to input color for border animation
      switch (this.props.daySelectionAnimation.type) {
        case "background":
          let dateViewBGColor = this.state.selected
            ? this.props.daySelectionAnimation.highlightColor
            : "transparent";
          dateViewStyle = { backgroundColor: dateViewBGColor };
          break;
        case "border":
          let dateViewBorderWidth = this.state.selected
            ? this.props.daySelectionAnimation.borderWidth
            : 0;
          dateViewStyle = {
            borderColor: this.props.daySelectionAnimation.borderHighlightColor,
            borderWidth: dateViewBorderWidth
          };
          break;
        default:
          // No animation styling by default
          break;
      }
```
in CalendarDay.js

**Comment by peacechen** [comment]
Would you provide a usage example?  A <CalendarStrip /> instance with all the prop values passed to it.

**Comment by thanh-dong** [comment]
hi @peacechen, The idea is I created a custom style for today, and animation for that date is not applied any more. The code likes:
`
const customDatesStyles = [{
        startDate: moment(),
        dateNameStyle: {color: 'red'},
        dateNumberStyle: {color: 'red'}
      }]; 
<CalendarStrip
              style={styles.calendarStrip}
              calendarHeaderStyle={styles.calendarHeaderStyle}
              calendarColor='#FDF3E8'
              dateNameStyle={styles.dateNameStyle}
              highlightDateNameStyle={[styles.dateNameStyle, styles.highlightDateNameStyle]}
              highlightDateNumberStyle={styles.highlightDateNameStyle}
              daySelectionAnimation={{
                type: 'background',
                highlightColor: '#EC870E'
              }}
              onDateSelected={this.onDateSelected}
              customDatesStyles={customDatesStyles}
          />
`

**Comment by thanh-dong** [comment]
great! thank you @peacechen. Btw, I have another question, is this possible to apply custom date styles while changing week? In the example we just apple for a week, what I want is re-evaluate the custom style when the week is changed.

**Comment by AleenaVJ** [comment]
Is it possible to set `customDatesStyles` dynamically? I tried to pass values as props. But it is working only when Debugger is on.

**Comment by peacechen** [comment]
Do the parent components use `shouldComponentUpdate` ?  It could be that the parent of `CalendaerStrip` is stopping updates from flowing down.  I've used `customDatesStyles` with dynamic data successfully before.
