### ISSUE TITLE
ComponentWillReceiveProps: Changes week if startingDate is not provided

### ISSUE THREAD

**Issue by tyricec** [BugiDev/react-native-calendar-strip#83]
Hi,

I noticed that there is an issue with componentWillReceiveProps when startingDate is undefined.

In my use case, I update the customDatesStyles dynamically which causes this snippet in CalendarStrip.js ([185](https://github.com/BugiDev/react-native-calendar-strip/blob/master/src/CalendarStrip.js#L185)) to run:

```js
 if (
      !updateState &&
      (JSON.stringify(nextProps.datesBlacklist) !==
        JSON.stringify(this.props.datesBlacklist) ||
        JSON.stringify(nextProps.datesWhitelist) !==
          JSON.stringify(this.props.datesWhitelist) ||
        JSON.stringify(nextProps.customDatesStyles) !==
          JSON.stringify(this.props.customDatesStyles))
    ) {
      updateState = true;
      // No need to update week start here
      startingDate = {
        startingDate: this.updateWeekStart(nextProps.startingDate)
      };
      weekData = this.updateWeekData(
        startingDate.startingDate,
        this.state.selectedDate,
        nextProps
      );
}
```

This causes the calendar to display the week that contains today's date. This is an issue when the user is viewing a week that is different than the week that contains today's date.

My patch for this was:

```js
 startingDate = {
        startingDate:  this.getInitialStartingDate()
      };
```

As this will ensure that if the startingDate is undefined, it will use the selectedDate to get the startingDate.

Here's how I am using the CalendarStrip component:

```js
<CalendarStrip
	{...this.defaultOptions}
	{...this.props}
	customDatesStyles={customDatesStyles}
	onCalendarHeaderPress={this.onCalendarHeaderPress}
	onDateLongPress={date => this.onDateLongPress(date)}
	onDateSelected={date => this.onDateSelected(date)}
	ref={(calendar) => { this.calendar = calendar; }}
	selectedDate={this.state.selectedDate}
	updateWeek
/>
```

**Comment by peacechen** [comment]
Thanks @tyricec for debugging this.  Would you mind creating a PR?

It may be a while until I get a chance to test the change under other use cases.  Do you think there are side effects to your change?

**Comment by tyricec** [comment]
I don't believe so. Will try to create some examples to test and see.

**Comment by peacechen** [comment]
@tyricec 
I believe that this change may cover cases that your change misses:
```
      startingDate = {
        startingDate: this.updateWeekStart(this.props.selectedDate || this.props.startingDate)
      };
```

Would you mind trying that in your app?

**Comment by tyricec** [comment]
Will try to look into it tonight. Apologies for forgetting about this ticket.

**Comment by tyricec** [comment]
```
startingDate = {
  startingDate: this.props.startingDate || this.props.selectedDate)
};
```

worked in my example. I can make a PR if you want.

**Comment by peacechen** [comment]
Yes that would be great. Thanks @tyricec
