### ISSUE TITLE
Return to current date whenever user returns to page

### ISSUE THREAD

**Issue by VanessaChu** [BugiDev/react-native-calendar-strip#90]
When I select a date such as Mar 1 (15 days ago) click on another tab, then return to the tab with the calendar strip, the highlighted selected date remains Mar 1. How do I make it such that it changes back to current date (Mar 16) ?

**Comment by brightboahen** [comment]
@VanessaChu have you tried using the ```selectedDate``` prop? Use the parent components lifecycle method to default the calendar to current date.

**Comment by brightboahen** [comment]
Could you share your code with me so I can help check how you’ve configured the calendar.

**Comment by VanessaChu** [comment]
I configured it like this. 
If I add the property: selectedDate = moment()
It won't run this._onDateSelected(date). Selected date will always be today's date.

```
              <CalendarStrip
                showMonth={false}
                onDateSelected={date => this._onDateSelected(date)}
                daySelectionAnimation={{ type: 'background', duration: 300, highlightColor: '#7B5E90' }}
                highlightDateNumberStyle={{ color: 'white', fontSize: 12 }}
                highlightDateNameStyle={{ color: 'white', fontSize: 8 }}
                maxDate={moment().tz(tz)}
                minDate={moment(res.created).tz(tz)}
                locale={locale}
              />
```

**Comment by peacechen** [comment]
Most tab navigators don't destroy tabs when another is selected.  This is for performance reasons so that the contents aren't repeatedly destroyed & created when tabs are selected.

It sounds like the CalendarStrip behavior is due to the instance remaining live in memory.  What you'll need to do is hook into the tab selection event and clear the selected date using [setSelectedDate(0)](https://github.com/BugiDev/react-native-calendar-strip#methods)

**Comment by brightboahen** [comment]
@peacechen will it have a different behaviour if she were to set both startingDate and selectedDate to the moment object returned anytime the onDateSelected method is called? E.g control the startingDate and startingDate through state.

**Comment by VanessaChu** [comment]
This is not working for me. In componentWillReceiveProps i try to detect that if route returns to the tab with the calendarstrip, i reset selected date with setSelectedDate(0)

```
  componentWillReceiveProps (nextProps) {
    console.log('Enter SummaryScreen.componentWillReceiveProps')
    if (nextProps.primaryNav.routes[0].index !== this.props.primaryNav.routes[0].index) {
      let index = nextProps.primaryNav.routes[0].index
      if (nextProps.primaryNav.routes[0].routes[index].routeName === 'SummaryScreen') {
        this.refs.myCalendarStrip.setSelectedDate(0)
      }
    }
  }
```
```

              <CalendarStrip
                ref={'myCalendarStrip'}
                showMonth={false}
                date={this.state.date}
                onDateSelected={date => this._onDateSelected(date)}
                daySelectionAnimation={{ type: 'background', duration: 300, highlightColor: '#7B5E90' }}
                highlightDateNumberStyle={{ color: 'white', fontSize: 12 }}
                highlightDateNameStyle={{ color: 'white', fontSize: 8 }}
                maxDate={moment().tz(tz)}
                minDate={moment(res.created).tz(tz)}
                locale={locale}
              />
```

**Comment by peacechen** [comment]
I think I uIt looks like you want to move the week back to the current date and clear the selected date since you're using`setSelectedDate(0)`.  Passing in `0` will only clear the highlighted date; it won't move the current week.
In that scenario, also call `updateWeekView( moment() )` to change the week to the current date.

**Comment by peacechen** [comment]
@brightboahen  It's possible to use the `startingDate` prop, but may take some experimentation to see how it behaves when the user changes the week changed.  As I recall, it can be problematic depending on when state updates occur in the parent and are propagated down to CalendarStrip (e.g. it may suddenly switch the week away from what the user has selected).

**Comment by brightboahen** [comment]
@VanessaChu try the snippet below, you may have to alter it but you should remove the date prop and use selectedDate as shown. You can then control the centering/showing of the week using the startingDate. In your case you can initialise it to the current date.
```javascript
class MyCalendarStrip extends Component {
   state = {
          weekStart: moment(),
          selectedDate: moment()
   }

  _handleOnWeekChange = (weekStart) => {
       // you can use this to control the centering/starting of the week 
       // or keep by default set to current day.
      this.setState({weekStart}); 
  }

   render() {
        return (
           <CalendarStrip
                  ref={'myCalendarStrip'}
                  showMonth={false}
                  date={this.state.date} // remove this prop
                  selectedDate={this.state.selectedDate}
                  startingDate={this.state.weekStart}
                  onWeekChange={this._handleOnWeekChange}
                  onDateSelected={selectedDate => this.setState({selectedDate})}
                  daySelectionAnimation={{ type: 'background', duration: 300, highlightColor: '#7B5E90' }}
                  highlightDateNumberStyle={{ color: 'white', fontSize: 12 }}
                  highlightDateNameStyle={{ color: 'white', fontSize: 8 }}
                  maxDate={moment().tz(tz)}
                  minDate={moment(res.created).tz(tz)}
                  locale={locale}
          />
       )
    }
}
```

**Comment by adilsonoj** [comment]
I configured it like this.


`<CalendarStrip
          style={{height: 90, paddingTop: 16}}
          calendarHeaderContainerStyle={{paddingBottom: 0}}
          calendarAnimation={{type: 'parallel', duration: 15}}
          daySelectionAnimation={{
            type: 'background',
            duration: 300,
            highlightColor: '#fff',
          }}
          startingDate={weekStart}
          onWeekChanged={week => setWeekStart(week)}
          customDatesStyles={customDatesStyles}
          markedDates={markedDates}
          onDateSelected={date => setDateSelected(date)}
        />`

**Comment by tiffanym19** [comment]
Please Help, I'm having an issue with this one :(

**Comment by peacechen** [comment]
I've refactored the code to better isolate CalendarDay logic.  It's on master but hasn't been released yet.  The internal methods might have slightly different behavior.  I would appreciate more testing on the master branch to see whether it fixes some of these issues or introduces new ones. 
Note that `updateWeekStart` doesn't update internal state, so moving to a given date may need new code.

I'm working on the scrollable feature which has taken a lot of time.  I plan to publish a new version when that's ready.

**Comment by peacechen** [comment]
The `updateWeekView` method has been restored in 2.0.0.
