### ISSUE TITLE
Only first digit shows up in date when months overlap

### ISSUE THREAD

**Issue by RShah512** [BugiDev/react-native-calendar-strip#91]
![whatsapp image 2018-03-26 at 3 48 32 pm](https://user-images.githubusercontent.com/10979006/37900943-54d5f9ea-310d-11e8-870e-aa147d69375f.jpeg)

Device: Android (issue not on all android devices, also works well on iOS)

Versions:
react-native: 0.50.1
react-native-calendar-strip: 1.3.0

**Comment by peacechen** [comment]
See #86

**Comment by RShah512** [comment]
@peacechen OnePlus

**Comment by fmoessle** [comment]
same here, only with oneplus3

**Comment by peacechen** [comment]
PR #106 may fix this.  I haven't heard any feedback from anyone about testing it, but I'll go ahead and publish it.  Please post your findings after updating.
