### ISSUE TITLE
Override customDate style when it is highlighted(selected)

### ISSUE THREAD

**Issue by jfrense** [BugiDev/react-native-calendar-strip#95]
I am marking other days with a different style  if I have an event for that day already scheduled. However when a User selects that day I still want the border that occurs when a date is selected. If I add a border to my customDate style then two dates have a border around them which I dont want to happen.

Is there a way for the highlighted style to override the custom date style when selected ? Or amybe merge the two styles with custom style + selected style?

**Comment by peacechen** [comment]
That would be a good feature to have.  Would you be willing to submit a PR?

**Comment by peacechen** [comment]
On reviewing the code and from my experience, the selected date style should override the custom style.  Have you tried setting borderWidth 0 for the selected date style?

**Comment by jfrense** [comment]
I jus tried your suggestion and it doesn't seem to be the case. For every date that I apply a customDateStyle too, when I select it and I have a different select style, the select style does not override the customDateStyle.

**Comment by peacechen** [comment]
Looks like the logic will need to be updated to prioritize the selected style.  Would you like to test it?  You'd need to point your package.json to this repo.

**Comment by jfrense** [comment]
@peacechen thanks for the fix. One issue I noticed is that the following components don't have any effect anymore
```
dateNumberStyle={{color: 'red'}}
dateNameStyle={{color: 'red'}}
```
for dates where the customDateStyle does not apply.

**Comment by peacechen** [comment]
Would you mind posting your `<CalendarStrip/>` code along with the props?   I think I see an issue and want to test it out before pushing another commit.
