### ISSUE TITLE
[Question] Is it possible to scroll through dates instead of tapping on arrows?

### ISSUE THREAD

**Issue by skmehra** [BugiDev/react-native-calendar-strip#96]
With all the customisations calendar strip looks great, I'm not sure if there is a way to swipe left/right to  view dates instead of tapping arrows to do so.

**Comment by peacechen** [comment]
Swipe has been implemented. It seems picky about when to recognize a swipe. See the documentation and inspect the code. If you have an improvement please create a PR.

**Comment by skmehra** [comment]
@peacechen I assume you are referring to LayoutAnimation, I went through the code but could not figure out a way to swipe through days. 
Sorry, I'm still experimenting through stuff to learn. Noob here, need help please.

**Comment by peacechen** [comment]
My apologies. Someone mentioned they did a swipe implementation but they never submitted a PR.  See #1

**Comment by peacechen** [comment]
This has been published in the 2.0.0 release.
